namespace SmokeLounge.AOtomation.Messaging.Tests
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Text.RegularExpressions;

    using AORebirth.Core.Playfields;

    using Microsoft.VisualStudio.TestTools.UnitTesting;

    using ZoneEngine.Core.Playfields;

    [TestClass]
    public class CapturedEnemyCombatProfileCatalogTests
    {
        public TestContext TestContext { get; set; }

        [TestMethod]
        public void GeneratedCatalogMatchesTheVersionedInventoryAndFailsClosedOnAmbiguousExactBindings()
        {
            string root = FindRepositoryRoot();
            string inventoryPath = Path.Combine(
                root,
                "docs",
                "generated",
                "capture_backed_npc_combat_inventory.json");
            string generatedPath = Path.Combine(
                root,
                "AORebirth",
                "Server",
                "ZoneEngine",
                "Core",
                "Playfields",
                "CapturedEnemyCombatProfileCatalog.g.cs");
            string inventoryHeader = ReadInventoryHeader(inventoryPath);
            CapturedEnemyCombatProfileDefinition[] profiles =
                CapturedEnemyCombatProfileCatalog.GetProfilesForTests();

            Assert.IsTrue(File.Exists(generatedPath));
            Assert.IsTrue(File.ReadAllText(generatedPath).StartsWith("// <auto-generated />"));
            Assert.AreEqual(3, ReadSummaryValue(inventoryHeader, "schemaVersion"));
            Assert.AreEqual(
                0,
                ReadSummaryValue(inventoryHeader, "recoverableEvidenceBlockers"),
                "No complete normal raw chain may remain unintegrated without a documented exclusion.");
            Assert.AreEqual(
                profiles.Length,
                ReadRuntimeGeneratedDefinitionCount(inventoryHeader));
            Assert.AreEqual(
                ReadRuntimeGeneratedDefinitionCount(inventoryHeader),
                CapturedEnemyCombatGeneratedPacketFixtures.Create().Length,
                "Every generated capture-certified inventory variant must have an exact-byte fixture.");
            Assert.IsTrue(profiles.Length > 15, "The generated catalog must supersede the 15-profile seed audit.");
            Assert.AreEqual(
                profiles.Length,
                profiles.Select(value => value.ProfileId).Distinct(StringComparer.Ordinal).Count());

            foreach (CapturedEnemyCombatProfileDefinition profile in profiles)
            {
                Assert.IsFalse(string.IsNullOrWhiteSpace(profile.ProfileId));
                Assert.IsFalse(string.IsNullOrWhiteSpace(profile.Evidence));
                Assert.IsTrue(profile.ResourceId > 0);
                Assert.IsFalse(string.IsNullOrWhiteSpace(profile.Name));
                Assert.IsTrue(profile.MonsterData > 0);
                Assert.IsTrue(profile.Level > 0);
                Assert.IsTrue(profile.SourceIdentities.Length > 0);
                Assert.AreEqual(
                    profile.SourceIdentities.Length,
                    profile.SourceIdentities.Distinct().Count(),
                    profile.ProfileId + " repeats a captured source identity.");
                Assert.IsTrue(profile.SourceIdentities.All(value => value != 0));
                CollectionAssert.Contains(
                    profile.SourceIdentities,
                    profile.RepresentativeEvidenceSourceIdentity);
                Assert.IsTrue(profile.Streams.Length > 0);

                if (profile.WeaponDefinition != null)
                {
                    Assert.IsTrue(
                        profile.WeaponDefinition.IsValid,
                        profile.ProfileId + " generated an invalid WIFU definition.");
                    CollectionAssert.Contains(
                        profile.SourceIdentities,
                        profile.WeaponDefinition.EvidenceSourceIdentity);
                }

                foreach (CapturedEnemyCombatProfileStreamDefinition stream in profile.Streams)
                {
                    Assert.IsTrue(stream.MinimumObservedDamage > 0);
                    Assert.IsTrue(stream.MaximumObservedDamage >= stream.MinimumObservedDamage);
                    Assert.IsTrue(stream.InitialAmmoCount >= -1);
                    Assert.AreEqual(3, stream.HitTypeWire);
                    Assert.IsTrue(stream.ObservedRechargeSeconds >= 0);
                    if (stream.WeaponSlot == 6 && stream.WeaponInstance == 0)
                    {
                        Assert.IsNotNull(
                            profile.WeaponDefinition,
                            profile.ProfileId + " uses the right-hand weapon slot without an owner-linked WIFU.");
                    }
                }
            }

            var exactBindings = profiles.SelectMany(
                profile => profile.SourceIdentities.Select(
                    source => new
                    {
                        Key = ExactBindingKey(profile, source),
                        Profile = profile,
                        SourceIdentity = source
                    })).ToArray();
            var ambiguousExactBindings = exactBindings
                .GroupBy(value => value.Key, StringComparer.Ordinal)
                .Where(group => group.Count() > 1)
                .ToArray();
            foreach (var ambiguousBinding in ambiguousExactBindings)
            {
                Assert.AreEqual(
                    ambiguousBinding.Count(),
                    ambiguousBinding.Select(value => value.Profile.ProfileId)
                        .Distinct(StringComparer.Ordinal)
                        .Count(),
                    "A duplicate exact binding repeated one generated packet variant.");
                Assert.IsTrue(
                    ambiguousBinding.All(value => !value.Profile.SemanticFallbackCaptureProven),
                    "An ambiguous exact binding must not claim a source-free fallback.");

                var representative = ambiguousBinding.First();
                CapturedEnemyCombatContract ambiguousResolved;
                string ambiguousFailure;
                Assert.IsFalse(
                    CapturedEnemyCombatProfileCatalog.TryResolve(
                        representative.Profile.ResourceId,
                        representative.Profile.Name,
                        representative.Profile.MonsterData,
                        representative.Profile.Level,
                        representative.SourceIdentity,
                        CapturedEnemyCombatContract.Unresolved("ambiguous exact binding", true),
                        out ambiguousResolved,
                        out ambiguousFailure),
                    "Capture-distinct variants sharing one source must fail closed.");
                Assert.IsFalse(ambiguousResolved.IsCombatReady);
                Assert.IsTrue(
                    ambiguousFailure.IndexOf(
                        "does not distinguish",
                        StringComparison.Ordinal) >= 0
                    || ambiguousFailure.IndexOf(
                        "explicitly unsafe",
                        StringComparison.Ordinal) >= 0,
                    ambiguousFailure);
            }

            Assert.IsFalse(
                profiles.Where(value => value.SemanticFallbackCaptureProven)
                    .GroupBy(SemanticKey, StringComparer.Ordinal)
                    .Any(group => group.Count() != 1),
                "More than one generated packet variant claims the same source-free semantic fallback.");

        }

        [TestMethod]
        public void InventoryDecodeErrorsAreExplicitAndNeverReusedAsMetadataProvenance()
        {
            string inventoryPath = Path.Combine(
                FindRepositoryRoot(),
                "docs",
                "generated",
                "capture_backed_npc_combat_inventory.json");
            string inventoryHeader = ReadInventoryHeader(inventoryPath);
            string inventoryJson = File.ReadAllText(inventoryPath);
            List<string> decodeErrors = ReadJsonArrayObjects(
                inventoryJson,
                "decodeOrProjectionErrors");
            Assert.AreEqual(
                ReadSummaryValue(inventoryHeader, "decodeOrProjectionErrors"),
                decodeErrors.Count);
            var metadataKeys = new HashSet<string>(
                ReadJsonArrayObjects(inventoryJson, "metadataGenerations").Select(
                    value => ReadJsonString(value, "capture")
                             + "|" + ReadJsonInt(value, "sequence")),
                StringComparer.Ordinal);
            foreach (string decodeError in decodeErrors)
            {
                string capture = ReadJsonString(decodeError, "capture");
                string artifact = ReadJsonString(decodeError, "artifact");
                int sequence = ReadJsonInt(decodeError, "sequence");
                string error = ReadJsonString(decodeError, "error");
                Assert.IsFalse(string.IsNullOrWhiteSpace(capture));
                Assert.IsFalse(string.IsNullOrWhiteSpace(artifact));
                Assert.IsTrue(sequence > 0);
                Assert.IsFalse(string.IsNullOrWhiteSpace(error));
                Assert.IsFalse(
                    metadataKeys.Contains(capture + "|" + sequence),
                    "An undecoded raw SCFU was reused as metadata provenance: "
                    + capture + " sequence=" + sequence);
            }
        }

        [TestMethod]
        public void RuntimeReadyStreamsRequireExactTimingDamageAndRangeSources()
        {
            CapturedEnemyCombatProfileDefinition[] profiles =
                CapturedEnemyCombatProfileCatalog.GetProfilesForTests();
            CapturedEnemyCombatProfileStreamDefinition[] readyStreams = profiles.SelectMany(
                profile => profile.Streams.Where(
                    stream => stream.HasCompleteFixedRuntimeEvidence
                              && stream.HasCaptureBackedAttackRange(
                                  profile.WeaponDefinition))).ToArray();

            Assert.IsTrue(readyStreams.Length > 0);
            foreach (CapturedEnemyCombatProfileDefinition profile in profiles)
            {
                foreach (CapturedEnemyCombatProfileStreamDefinition stream in profile.Streams)
                {
                    if (!stream.HasCompleteFixedRuntimeEvidence
                        || !stream.HasCaptureBackedAttackRange(profile.WeaponDefinition))
                    {
                        continue;
                    }

                    Assert.IsTrue(stream.CapturedDamageObservations.Length > 0);
                    Assert.IsTrue(stream.CapturedAttackStartDelayObservationsSeconds.Length > 0);
                    Assert.AreEqual(
                        stream.CapturedAttackStartDelayObservationsSeconds.Length,
                        stream.CapturedFirstHitDelayObservationsSeconds.Length);
                    if (!stream.CapturedAttackRange.HasValue)
                    {
                        Assert.IsTrue(stream.CapturedUsesEquippedWeapon == true);
                        Assert.IsNotNull(profile.WeaponDefinition);
                        Assert.IsTrue(profile.WeaponDefinition.IsValid);
                        Assert.AreEqual(0, stream.WeaponInstance);
                        Assert.AreEqual(
                            profile.WeaponDefinition.InventorySlot,
                            stream.WeaponSlot);
                    }
                }
            }
        }

        [TestMethod]
        public void SpecializedMatchingRequiresDistinctStreamsAndRepeatingFirstHitEvidence()
        {
            CapturedEnemyCombatAttackDefinition duplicatePhase =
                CreateSpecializedTestAttack(10, 2.0d);
            Assert.IsFalse(
                new CapturedEnemyParallelAttackStreamDefinition(-0.1d, duplicatePhase).IsValid,
                "A negative parallel-stream initial delay must fail exactly as production does.");
            CapturedEnemyCombatContract parallelContract =
                CapturedEnemyCombatContract.CapturedParallelAttackSequence(
                    "bijective matching test",
                    new CapturedEnemyParallelAttackSequenceDefinition(
                        new[]
                        {
                            new CapturedEnemyParallelAttackStreamDefinition(1.0d, duplicatePhase),
                            new CapturedEnemyParallelAttackStreamDefinition(1.0d, duplicatePhase)
                        },
                        new CapturedEnemySpecialAttackDefinition[0],
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0));
            CapturedEnemyCombatProfileDefinition oneStream = CreateSpecializedTestProfile(
                CreateSpecializedTestStream(10, 2.0d, 1.0d));
            Assert.IsFalse(
                oneStream.MatchesSpecialized(parallelContract),
                "One raw stream must not certify two specialized phases.");

            CapturedEnemyCombatAttackDefinition opening = CreateSpecializedTestAttack(10, 2.0d);
            CapturedEnemyCombatAttackDefinition repeating = CreateSpecializedTestAttack(20, 3.0d);
            CapturedEnemyCombatContract contract = CreateSpecializedTestContract(
                1.0d,
                opening,
                repeating);

            CapturedEnemyCombatProfileDefinition wrongRepeatingFirstHit =
                CreateSpecializedTestProfile(
                    CreateSpecializedTestStream(10, 2.0d, 1.0d),
                    CreateSpecializedTestStream(20, 3.0d, 99.0d));
            Assert.IsFalse(
                wrongRepeatingFirstHit.MatchesSpecialized(contract),
                "Repeating first-hit evidence must not be bypassed.");

            CapturedEnemyCombatProfileDefinition exactBijection = CreateSpecializedTestProfile(
                CreateSpecializedTestStream(10, 2.0d, 1.0d),
                CreateSpecializedTestStream(20, 3.0d, 3.0d));
            Assert.IsTrue(exactBijection.MatchesSpecialized(contract));

            CapturedEnemyCombatProfileDefinition runtimeUnsafe =
                CreateSpecializedTestProfileWithRuntimeSafety(
                    false,
                    CreateSpecializedTestStream(10, 2.0d, 1.0d),
                    CreateSpecializedTestStream(20, 3.0d, 3.0d));
            Assert.IsFalse(
                runtimeUnsafe.MatchesSpecialized(contract),
                "A stream rejected by capture extraction must not certify a specialized runtime.");
            CapturedEnemyCombatProfileDefinition ambiguousRuntimeInitialization =
                CreateSpecializedTestProfileWithRuntimeGates(
                    true,
                    false,
                    CreateSpecializedTestStream(10, 2.0d, 1.0d),
                    CreateSpecializedTestStream(20, 3.0d, 3.0d));
            Assert.IsFalse(
                ambiguousRuntimeInitialization.MatchesSpecialized(contract),
                "Mutable WIFU/SAW initialization must be deterministic before runtime enrichment.");
        }

        [TestMethod]
        public void SpecializedMatchingEnrichesNoncontinuousDamageInCapturedOrderAndFailsClosedOnAttackInfoMismatch()
        {
            CapturedEnemyCombatAttackDefinition attack = CreateSpecializedTestAttack(
                10,
                12,
                2.0d,
                9.5d,
                0);
            CapturedEnemyCombatContract contract =
                CapturedEnemyCombatContract.CapturedParallelAttackSequence(
                    "noncontinuous specialized replay test",
                    new CapturedEnemyParallelAttackSequenceDefinition(
                        new[]
                        {
                            new CapturedEnemyParallelAttackStreamDefinition(1.0d, attack)
                        },
                        new CapturedEnemySpecialAttackDefinition[0],
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0));
            int[] orderedDamageObservations = { 10, 12, 10, 12 };
            CapturedEnemyCombatProfileStreamDefinition fixedReplayStream =
                CreateSpecializedTestStream(
                    10,
                    12,
                    orderedDamageObservations,
                    2.0d,
                    1.0d,
                    9.5d);
            Assert.IsTrue(
                fixedReplayStream.Matches(
                    attack,
                    0.0d,
                    1.0d,
                    new[] { 2.0d },
                    null),
                "A fixed replay backed by ordered observations must not require every integer in the damage envelope.");
            CapturedEnemyCombatProfileDefinition missingRangeProfile = CreateSpecializedTestProfile(
                CreateSpecializedTestStream(
                    10,
                    12,
                    orderedDamageObservations,
                    2.0d,
                    1.0d,
                    null));

            CapturedEnemyCombatContract enriched;
            Assert.IsFalse(
                missingRangeProfile.TryEnrichSpecialized(contract, out enriched),
                "A specialized baseline must not substitute its own unproven maximum attack range.");
            Assert.IsNull(enriched);

            CapturedEnemyCombatProfileDefinition profile = CreateSpecializedTestProfile(
                CreateSpecializedTestStream(
                    10,
                    12,
                    orderedDamageObservations,
                    2.0d,
                    1.0d,
                    9.5d));
            Assert.IsTrue(profile.TryEnrichSpecialized(contract, out enriched));
            Assert.IsNotNull(enriched);
            CollectionAssert.AreEqual(
                orderedDamageObservations,
                enriched.ParallelAttackSequence.Streams[0].Attack.CapturedDamageObservations);
            Assert.AreEqual(9.5d, enriched.ParallelAttackSequence.Streams[0].Attack.Range);
            Assert.AreEqual(1.0d, enriched.ParallelAttackSequence.Streams[0].InitialDelaySeconds);
            Assert.AreEqual(2.0d, enriched.ParallelAttackSequence.Streams[0].Attack.RechargeSeconds);
            Assert.AreEqual(
                0,
                attack.CapturedDamageObservations.Length,
                "Capture certification must enrich a clone instead of mutating the existing contract.");
            CollectionAssert.DoesNotContain(
                enriched.ParallelAttackSequence.Streams[0].Attack.CapturedDamageObservations,
                11,
                "Runtime replay must not synthesize an uncaptured value inside the observed envelope.");

            CapturedEnemyCombatAttackDefinition attackInfoMismatch = CreateSpecializedTestAttack(
                10,
                12,
                2.0d,
                9.5d,
                99);
            CapturedEnemyCombatContract mismatchedContract =
                CapturedEnemyCombatContract.CapturedParallelAttackSequence(
                    "specialized packet mismatch test",
                    new CapturedEnemyParallelAttackSequenceDefinition(
                        new[]
                        {
                            new CapturedEnemyParallelAttackStreamDefinition(
                                1.0d,
                                attackInfoMismatch)
                        },
                        new CapturedEnemySpecialAttackDefinition[0],
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0));
            Assert.IsFalse(profile.TryEnrichSpecialized(mismatchedContract, out enriched));
            Assert.IsNull(enriched);
        }

        [TestMethod]
        public void GeneratedRuntimeUnsafeProfilesAreNeverSelected()
        {
            CapturedEnemyCombatProfileDefinition[] allProfiles =
                CapturedEnemyCombatProfileCatalog.GetProfilesForTests();
            CapturedEnemyCombatProfileDefinition[] unsafeProfiles =
                allProfiles.Where(
                    value => !value.CaptureRuntimeEvidenceSafe).ToArray();
            Assert.IsTrue(unsafeProfiles.Length > 0);

            foreach (CapturedEnemyCombatProfileDefinition profile in unsafeProfiles)
            {
                CapturedEnemyCombatContract resolved;
                string failure;
                bool success = CapturedEnemyCombatProfileCatalog.TryResolve(
                    profile.ResourceId,
                    profile.Name,
                    profile.MonsterData,
                    profile.Level,
                    profile.RepresentativeEvidenceSourceIdentity,
                    CapturedEnemyCombatContract.Unresolved("runtime-safety test baseline", true),
                    out resolved,
                    out failure);
                if (success)
                {
                    CapturedEnemyCombatProfileDefinition selected = allProfiles.Single(
                        value => value.MatchesKey(
                                     profile.ResourceId,
                                     profile.Name,
                                     profile.MonsterData,
                                     profile.Level)
                                 && value.CaptureRuntimeEvidenceSafe
                                 && value.Evidence == resolved.Evidence
                                 && value.ContainsSource(resolved.EvidenceSourceIdentity));
                    Assert.AreNotEqual(profile.ProfileId, selected.ProfileId);
                    Assert.IsTrue(resolved.IsCombatReady);
                    continue;
                }

                Assert.IsFalse(resolved.IsCombatReady);
                Assert.IsFalse(string.IsNullOrWhiteSpace(failure));
            }
        }

        [TestMethod]
        public void FixedStartSchedulingEmitsSawBeforeDelayedAttackWithoutAReleaseTick()
        {
            string coordinator = File.ReadAllText(
                Path.Combine(
                    FindRepositoryRoot(),
                    "AORebirth",
                    "Server",
                    "ZoneEngine",
                    "Core",
                    "Playfields",
                    "NpcCombatTickCoordinator.cs"));
            string reset = Slice(
                coordinator,
                "internal void ResetCombatTick",
                "internal void ClearTracking");
            int sawAtFightStart = reset.IndexOf(
                "AnnounceCapturedEnemySpecialAttackWeaponContext(",
                StringComparison.Ordinal);
            int delayedAttackRegistration = reset.IndexOf(
                "pendingCapturedAttackStarts[",
                StringComparison.Ordinal);
            Assert.IsTrue(sawAtFightStart >= 0);
            Assert.IsTrue(delayedAttackRegistration > sawAtFightStart);

            string process = Slice(
                coordinator,
                "internal void ProcessCombatTick",
                "private bool TryApplyCapturedWeaponAmmo");
            int fixedRelease = process.IndexOf(
                "fixedAttackStartReleased = true;",
                StringComparison.Ordinal);
            int pendingRemoval = process.IndexOf(
                "pendingCapturedAttackStarts.Remove",
                StringComparison.Ordinal);
            int conditionalReturn = process.IndexOf(
                "if (!fixedAttackStartReleased)",
                StringComparison.Ordinal);
            Assert.IsTrue(fixedRelease >= 0);
            Assert.IsTrue(pendingRemoval > fixedRelease);
            Assert.IsTrue(conditionalReturn > pendingRemoval);
        }

        [TestMethod]
        public void SingleStreamDefinitionsResolveOrRetainAnExactCorpusBackedUnresolvedRecord()
        {
            string root = FindRepositoryRoot();
            Dictionary<string, string> inventoryProfiles = ReadInventoryProfiles(
                Path.Combine(
                    root,
                    "docs",
                    "generated",
                    "capture_backed_npc_combat_inventory.json"));
            CapturedEnemyCombatProfileDefinition[] profiles =
                CapturedEnemyCombatProfileCatalog.GetProfilesForTests();
            CapturedEnemyCombatProfileDefinition[] singleStream = profiles.Where(
                value => value.Streams.Length == 1).ToArray();
            Assert.IsTrue(singleStream.Length > 0);
            CapturedEnemyCombatProfileDefinition uniqueCompatibleRepresentative =
                singleStream.First(
                    profile => profile.CaptureRuntimeEvidenceSafe
                               && profiles.Count(
                                   value => value.MatchesKey(
                                                profile.ResourceId,
                                                profile.Name,
                                                profile.MonsterData,
                                                profile.Level)
                                            && value.CaptureRuntimeEvidenceSafe) == 1);
            foreach (CapturedEnemyCombatProfileDefinition profile in singleStream)
            {
                foreach (int sourceIdentity in profile.SourceIdentities)
                {
                    CapturedEnemyCombatContract resolved;
                    string failure;
                    bool success = CapturedEnemyCombatProfileCatalog.TryResolve(
                        profile.ResourceId,
                        profile.Name,
                        profile.MonsterData,
                        profile.Level,
                        sourceIdentity,
                        CapturedEnemyCombatContract.Unresolved("test baseline", true),
                        out resolved,
                        out failure);

                    if (!success)
                    {
                        Assert.IsFalse(string.IsNullOrWhiteSpace(failure));
                        Assert.IsTrue(
                            HasExactInventoryRecord(inventoryProfiles, profile, sourceIdentity),
                            profile.ProfileId
                            + " source " + sourceIdentity.ToString("X8")
                            + " is neither runtime-resolvable nor represented by exact corpus evidence: "
                            + failure);
                        continue;
                    }

                    Assert.IsTrue(resolved.IsCombatReady);
                    CapturedEnemyCombatProfileDefinition selected = profiles.Single(
                        value => value.MatchesKey(
                                     profile.ResourceId,
                                     profile.Name,
                                     profile.MonsterData,
                                     profile.Level)
                                 && value.CaptureRuntimeEvidenceSafe
                                 && value.Evidence == resolved.Evidence
                                 && value.ContainsSource(resolved.EvidenceSourceIdentity));
                    if (selected.ContainsSource(sourceIdentity))
                    {
                        Assert.AreEqual(sourceIdentity, resolved.EvidenceSourceIdentity);
                    }
                    else
                    {
                        Assert.AreEqual(
                            1,
                            profiles.Count(
                                value => value.MatchesKey(
                                             profile.ResourceId,
                                             profile.Name,
                                             profile.MonsterData,
                                             profile.Level)
                                         && value.CaptureRuntimeEvidenceSafe));
                        Assert.AreEqual(
                            selected.RepresentativeEvidenceSourceIdentity,
                            resolved.EvidenceSourceIdentity);
                    }

                    if (resolved.WeaponDefinition != null)
                    {
                        Assert.AreEqual(
                            resolved.EvidenceSourceIdentity,
                            resolved.WeaponDefinition.EvidenceSourceIdentity);
                    }
                }
            }

            Assert.IsNotNull(uniqueCompatibleRepresentative);
            CapturedEnemyCombatContract semantic;
            string semanticFailure;
            Assert.IsTrue(
                CapturedEnemyCombatProfileCatalog.TryResolve(
                    uniqueCompatibleRepresentative.ResourceId,
                    uniqueCompatibleRepresentative.Name,
                    uniqueCompatibleRepresentative.MonsterData,
                    uniqueCompatibleRepresentative.Level,
                    0,
                    CapturedEnemyCombatContract.Unresolved("test baseline", true),
                    out semantic,
                    out semanticFailure),
                semanticFailure);
            Assert.IsTrue(semantic.IsCombatReady);

            CapturedEnemyCombatContract rejected;
            string rejectedFailure;
            int unknownLevel = FindUnknownLevel(
                uniqueCompatibleRepresentative,
                profiles);
            Assert.IsFalse(
                CapturedEnemyCombatProfileCatalog.TryResolve(
                    uniqueCompatibleRepresentative.ResourceId,
                    uniqueCompatibleRepresentative.Name,
                    uniqueCompatibleRepresentative.MonsterData,
                    unknownLevel,
                    uniqueCompatibleRepresentative.SourceIdentities[0],
                    CapturedEnemyCombatContract.Unresolved("test baseline", true),
                    out rejected,
                    out rejectedFailure));
            Assert.IsFalse(rejected.IsCombatReady);
            Assert.IsFalse(string.IsNullOrWhiteSpace(rejectedFailure));

            int unknownSource = FindUnknownSource(
                uniqueCompatibleRepresentative.SourceIdentities);
            Assert.IsTrue(
                CapturedEnemyCombatProfileCatalog.TryResolve(
                    uniqueCompatibleRepresentative.ResourceId,
                    uniqueCompatibleRepresentative.Name,
                    uniqueCompatibleRepresentative.MonsterData,
                    uniqueCompatibleRepresentative.Level,
                    unknownSource,
                    CapturedEnemyCombatContract.Unresolved("test baseline", true),
                    out rejected,
                    out rejectedFailure),
                rejectedFailure);
            Assert.IsTrue(rejected.IsCombatReady);
            Assert.AreEqual(
                uniqueCompatibleRepresentative.RepresentativeEvidenceSourceIdentity,
                rejected.EvidenceSourceIdentity);
            Assert.AreNotEqual(unknownSource, rejected.EvidenceSourceIdentity);

            IGrouping<string, CapturedEnemyCombatProfileDefinition> ambiguous = profiles
                .GroupBy(SemanticKey, StringComparer.Ordinal)
                .First(group => group.Count(value => value.CaptureRuntimeEvidenceSafe) > 1);
            CapturedEnemyCombatProfileDefinition ambiguousRepresentative = ambiguous.First(
                value => value.CaptureRuntimeEvidenceSafe);
            Assert.IsFalse(
                CapturedEnemyCombatProfileCatalog.TryResolve(
                    ambiguousRepresentative.ResourceId,
                    ambiguousRepresentative.Name,
                    ambiguousRepresentative.MonsterData,
                    ambiguousRepresentative.Level,
                    0,
                    CapturedEnemyCombatContract.Unresolved("test baseline", true),
                    out rejected,
                    out rejectedFailure));
            Assert.IsFalse(rejected.IsCombatReady);
            StringAssert.Contains(rejectedFailure, "ambiguous");
        }

        [TestMethod]
        public void UniqueCultistProfileResolvesWithoutCapturedSourceIdentityMatch()
        {
            const int runtimeSourceIdentity = unchecked((int)0x79834DCF);
            CapturedEnemyCombatProfileDefinition profile =
                CapturedEnemyCombatProfileCatalog.GetProfilesForTests().Single(
                    value => value.ProfileId
                             == "5643a4bd8a3aaf44-9ce155283cfcc36c");
            Assert.AreEqual(1931, profile.ResourceId);
            Assert.AreEqual("Cultist", profile.Name);
            Assert.AreEqual(26103, profile.MonsterData);
            Assert.AreEqual(28, profile.Level);
            Assert.IsFalse(profile.ContainsSource(runtimeSourceIdentity));
            Assert.IsFalse(profile.SemanticFallbackCaptureProven);

            CapturedEnemyCombatContract resolved;
            string failure;
            Assert.IsTrue(
                CapturedEnemyCombatProfileCatalog.TryResolve(
                    1931,
                    "Cultist",
                    26103,
                    28,
                    runtimeSourceIdentity,
                    CapturedEnemyCombatContract.Unresolved(
                        "active totw.cultist.26103 source 0x79834DCF",
                        true),
                    out resolved,
                    out failure),
                failure);
            Assert.IsTrue(resolved.IsCombatReady);
            Assert.AreEqual(profile.Evidence, resolved.Evidence);
            Assert.AreEqual(
                profile.RepresentativeEvidenceSourceIdentity,
                resolved.EvidenceSourceIdentity);
        }

        [TestMethod]
        public void ActiveSubwayAndTempleSpawnsAreEitherExactSourceCertifiedOrFailClosed()
        {
            string root = FindRepositoryRoot();
            Dictionary<string, string> inventoryProfiles = ReadInventoryProfiles(
                Path.Combine(
                    root,
                    "docs",
                    "generated",
                    "capture_backed_npc_combat_inventory.json"));
            HashSet<string> inventoryMetadataBindings = ReadInventoryMetadataBindings(
                Path.Combine(
                    root,
                    "docs",
                    "generated",
                    "capture_backed_npc_combat_inventory.json"));
            var temple = new CapturedTempleOfThreeWindsContentProvider();
            var catalog = new OrdinaryEnemyCatalog(
                new CapturedSubwayContentProvider(),
                new CapturedSubwayOrdinaryContentProvider(),
                temple);
            Dictionary<string, OrdinaryEnemyProfile> profiles = catalog.GetProfiles()
                .ToDictionary(value => value.ProfileKey, StringComparer.Ordinal);
            CapturedEnemyCombatProfileDefinition[] generatedProfiles =
                CapturedEnemyCombatProfileCatalog.GetProfilesForTests();
            OrdinaryEnemySpawnDefinition[] spawns = catalog.GetSpawns()
                .Where(value => value.PlayfieldInstance == 127 || value.PlayfieldInstance == 1931)
                .ToArray();
            var failures = new List<string>();
            int certified = 0;
            int quarantined = 0;
            int subwayCertified = 0;
            int subwayQuarantined = 0;
            int templeCertified = 0;
            int templeQuarantined = 0;

            Assert.AreEqual(322, spawns.Count(value => value.PlayfieldInstance == 127));
            Assert.AreEqual(153, spawns.Count(value => value.PlayfieldInstance == 1931));
            foreach (OrdinaryEnemySpawnDefinition spawn in spawns)
            {
                OrdinaryEnemyProfile profile = profiles[spawn.ProfileKey];
                CapturedEnemyCombatContract baseline = profile.Combat.ResolveContract(
                    spawn.SourceIdentity,
                    spawn.Level);
                baseline.Retaliates = true;
                baseline.AiProfile = ZoneEngine.Core.NpcAiProfile.Passive;
                CapturedEnemyCombatContract resolved;
                string failure;
                bool success = CapturedEnemyCombatProfileCatalog.TryResolve(
                    spawn.PlayfieldInstance,
                    profile.DisplayName,
                    profile.MonsterData,
                    spawn.Level,
                    spawn.SourceIdentity,
                    baseline,
                    out resolved,
                    out failure);
                if (success)
                {
                    certified++;
                    if (spawn.PlayfieldInstance == 127) subwayCertified++;
                    else templeCertified++;
                    Assert.IsTrue(resolved.IsCombatReady);
                    CapturedEnemyCombatProfileDefinition[] keyMatches = generatedProfiles.Where(
                        value => value.MatchesKey(
                            spawn.PlayfieldInstance,
                            profile.DisplayName,
                            profile.MonsterData,
                            spawn.Level)).ToArray();
                    CapturedEnemyCombatProfileDefinition[] evidenceMatches = keyMatches.Where(
                        value => value.ContainsSource(
                            resolved.EvidenceSourceIdentity)).ToArray();
                    CapturedEnemyCombatProfileDefinition[] compatibleKeyMatches =
                        keyMatches.Where(value => value.CaptureRuntimeEvidenceSafe).ToArray();
                    Assert.AreEqual(1, evidenceMatches.Length);
                    if (compatibleKeyMatches.Any(
                            value => value.ContainsSource(spawn.SourceIdentity)))
                    {
                        Assert.AreEqual(spawn.SourceIdentity, resolved.EvidenceSourceIdentity);
                    }
                    else
                    {
                        Assert.AreEqual(1, compatibleKeyMatches.Length);
                        Assert.AreEqual(
                            evidenceMatches[0].RepresentativeEvidenceSourceIdentity,
                            resolved.EvidenceSourceIdentity);
                    }
                }
                else
                {
                    quarantined++;
                    if (spawn.PlayfieldInstance == 127) subwayQuarantined++;
                    else templeQuarantined++;
                    Assert.IsFalse(string.IsNullOrWhiteSpace(failure));
                    Assert.IsTrue(
                        HasExactInventoryRecord(
                            inventoryProfiles,
                            spawn.PlayfieldInstance,
                            profile.DisplayName,
                            profile.MonsterData,
                            spawn.Level,
                            spawn.SourceIdentity)
                        || inventoryMetadataBindings.Contains(
                            ExactBindingKey(
                                spawn.PlayfieldInstance,
                                profile.DisplayName,
                                profile.MonsterData,
                                spawn.Level,
                                spawn.SourceIdentity)),
                        "Active binding lacks an exact corpus-backed unresolved record: resource="
                        + spawn.PlayfieldInstance
                        + " name=" + profile.DisplayName
                        + " md=" + profile.MonsterData
                        + " level=" + spawn.Level
                        + " source=" + spawn.SourceIdentity.ToString("X8")
                        + " reason=" + failure);
                    failures.Add(
                        spawn.SpawnKey
                        + " source=" + spawn.SourceIdentity.ToString("X8")
                        + " name=" + profile.DisplayName
                        + " md=" + profile.MonsterData
                        + " level=" + spawn.Level
                        + ": " + failure);
                }
            }

            Assert.AreEqual(spawns.Length, certified + quarantined);
            Assert.IsTrue(
                certified > 15,
                "The generated corpus did not improve active dungeon certification beyond the seed audit. "
                + string.Join(" | ", failures.Take(5).ToArray()));
            this.TestContext.WriteLine(
                "PF127 certified={0} quarantined={1}; PF1931 certified={2} quarantined={3}; total certified={4} quarantined={5}",
                subwayCertified,
                subwayQuarantined,
                templeCertified,
                templeQuarantined,
                certified,
                quarantined);
        }

        private static CapturedEnemyCombatAttackDefinition CreateSpecializedTestAttack(
            int damage,
            double rechargeSeconds)
        {
            return CreateSpecializedTestAttack(
                damage,
                damage,
                rechargeSeconds,
                4.0d,
                0);
        }

        private static CapturedEnemyCombatAttackDefinition CreateSpecializedTestAttack(
            int minDamage,
            int maxDamage,
            double rechargeSeconds,
            double range,
            int attackInfoUnknown)
        {
            return new CapturedEnemyCombatAttackDefinition(
                minDamage,
                maxDamage,
                0,
                range,
                rechargeSeconds,
                false,
                -1,
                0,
                attackInfoUnknown,
                3,
                0,
                0,
                true);
        }

        private static CapturedEnemyCombatProfileStreamDefinition CreateSpecializedTestStream(
            int damage,
            double rechargeSeconds,
            double firstHitDelaySeconds)
        {
            return CreateSpecializedTestStream(
                damage,
                damage,
                new[] { damage },
                rechargeSeconds,
                firstHitDelaySeconds,
                4.0d);
        }

        private static CapturedEnemyCombatProfileStreamDefinition CreateSpecializedTestStream(
            int minDamage,
            int maxDamage,
            int[] capturedDamageObservations,
            double rechargeSeconds,
            double firstHitDelaySeconds,
            double? capturedAttackRange)
        {
            return new CapturedEnemyCombatProfileStreamDefinition(
                minDamage,
                maxDamage,
                -1,
                0,
                0,
                3,
                0,
                0,
                rechargeSeconds,
                capturedDamageObservations,
                new[] { 0.0d },
                new[] { firstHitDelaySeconds },
                new[] { rechargeSeconds },
                0,
                false,
                capturedAttackRange,
                true);
        }

        private static CapturedEnemyCombatContract CreateSpecializedTestContract(
            double initialAttackDelaySeconds,
            CapturedEnemyCombatAttackDefinition opening,
            CapturedEnemyCombatAttackDefinition repeating)
        {
            CapturedEnemyCombatContract contract = CapturedEnemyCombatContract.CapturedSpecialSequence(
                "specialized matching test",
                new CapturedEnemySpecialAttackSequenceDefinition(
                    initialAttackDelaySeconds,
                    opening,
                    repeating,
                    new CapturedEnemySpecialAttackDefinition[0],
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0));
            contract.HasCapturedAttackStartContext = true;
            contract.AttackStartDelaySeconds = 0.0d;
            return contract;
        }

        private static CapturedEnemyCombatProfileDefinition CreateSpecializedTestProfile(
            params CapturedEnemyCombatProfileStreamDefinition[] streams)
        {
            return CreateSpecializedTestProfileWithRuntimeSafety(true, streams);
        }

        private static CapturedEnemyCombatProfileDefinition CreateSpecializedTestProfileWithRuntimeSafety(
            bool captureRuntimeEvidenceSafe,
            params CapturedEnemyCombatProfileStreamDefinition[] streams)
        {
            return CreateSpecializedTestProfileWithRuntimeGates(
                captureRuntimeEvidenceSafe,
                true,
                streams);
        }

        private static CapturedEnemyCombatProfileDefinition CreateSpecializedTestProfileWithRuntimeGates(
            bool captureEvidenceSafe,
            bool deterministicRuntimeInitializationProven,
            params CapturedEnemyCombatProfileStreamDefinition[] streams)
        {
            return new CapturedEnemyCombatProfileDefinition(
                "specialized-test",
                "specialized matching test",
                127,
                "Specialized Test",
                1,
                1,
                true,
                captureEvidenceSafe,
                deterministicRuntimeInitializationProven,
                new[] { 1 },
                1,
                null,
                new CapturedEnemySpecialAttackDefinition[0],
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                streams);
        }

        private static string Slice(string text, string start, string end)
        {
            int startIndex = text.IndexOf(start, StringComparison.Ordinal);
            Assert.IsTrue(startIndex >= 0, "Missing source marker: " + start);
            int endIndex = text.IndexOf(end, startIndex + start.Length, StringComparison.Ordinal);
            Assert.IsTrue(endIndex > startIndex, "Missing source marker: " + end);
            return text.Substring(startIndex, endIndex - startIndex);
        }

        private static string SemanticKey(CapturedEnemyCombatProfileDefinition profile)
        {
            return string.Join(
                "|",
                profile.ResourceId,
                profile.Name,
                profile.MonsterData,
                profile.Level);
        }

        private static string ExactBindingKey(
            CapturedEnemyCombatProfileDefinition profile,
            int sourceIdentity)
        {
            return SemanticKey(profile) + "|" + sourceIdentity;
        }

        private static int FindUnknownSource(IEnumerable<int> capturedSources)
        {
            var occupied = new HashSet<int>(capturedSources);
            int candidate = unchecked((int)0x7F000001);
            while (occupied.Contains(candidate))
            {
                candidate++;
            }

            return candidate;
        }

        private static int FindUnknownLevel(
            CapturedEnemyCombatProfileDefinition profile,
            IEnumerable<CapturedEnemyCombatProfileDefinition> profiles)
        {
            var occupied = new HashSet<int>(
                profiles.Where(
                    value => value.ResourceId == profile.ResourceId
                             && value.MonsterData == profile.MonsterData
                             && string.Equals(value.Name, profile.Name, StringComparison.Ordinal))
                    .Select(value => value.Level));
            int candidate = 1;
            while (occupied.Contains(candidate))
            {
                candidate++;
            }

            return candidate;
        }

        private static bool HasExactInventoryRecord(
            IDictionary<string, string> inventoryProfiles,
            CapturedEnemyCombatProfileDefinition profile,
            int sourceIdentity)
        {
            return HasExactInventoryRecord(
                inventoryProfiles,
                profile.ResourceId,
                profile.Name,
                profile.MonsterData,
                profile.Level,
                sourceIdentity);
        }

        private static bool HasExactInventoryRecord(
            IDictionary<string, string> inventoryProfiles,
            int resourceId,
            string name,
            int monsterData,
            int level,
            int sourceIdentity)
        {
            string profileKey = string.Format(
                "resource={0}|md={1}|level={2}|name={3}",
                resourceId,
                monsterData,
                level,
                name);
            string profileJson;
            return inventoryProfiles.TryGetValue(profileKey, out profileJson)
                   && profileJson.IndexOf(
                       "0x" + unchecked((uint)sourceIdentity).ToString("X8"),
                       StringComparison.Ordinal) >= 0;
        }

        private static HashSet<string> ReadInventoryMetadataBindings(string path)
        {
            string json = File.ReadAllText(path);
            Dictionary<int, int> realmMap = ReadCapturedRealmMap(ReadInventoryHeader(path));
            var result = new HashSet<string>(StringComparer.Ordinal);
            foreach (string metadata in ReadJsonArrayObjects(json, "metadataGenerations"))
            {
                int capturedRealmId = ReadJsonInt(metadata, "capturedRealmId");
                int resourceId;
                if (!realmMap.TryGetValue(capturedRealmId, out resourceId))
                {
                    continue;
                }

                string sourceIdentity = ReadJsonString(metadata, "sourceIdentity");
                uint parsedSource;
                if (!sourceIdentity.StartsWith("0x", StringComparison.Ordinal)
                    || !uint.TryParse(
                        sourceIdentity.Substring(2),
                        System.Globalization.NumberStyles.HexNumber,
                        System.Globalization.CultureInfo.InvariantCulture,
                        out parsedSource))
                {
                    continue;
                }

                result.Add(
                    ExactBindingKey(
                        resourceId,
                        ReadJsonString(metadata, "name"),
                        ReadJsonInt(metadata, "monsterData"),
                        ReadJsonInt(metadata, "level"),
                        unchecked((int)parsedSource)));
            }

            return result;
        }

        private static Dictionary<int, int> ReadCapturedRealmMap(string inventoryHeader)
        {
            int name = inventoryHeader.IndexOf(
                "\"capturedRealmToRuntimeResource\"",
                StringComparison.Ordinal);
            Assert.IsTrue(name >= 0);
            int start = inventoryHeader.IndexOf('{', name);
            int end = inventoryHeader.IndexOf('}', start);
            Assert.IsTrue(start >= 0 && end > start);
            string mapJson = inventoryHeader.Substring(start, end - start + 1);
            var result = new Dictionary<int, int>();
            foreach (Match match in Regex.Matches(
                mapJson,
                "\\\"(?<realm>[0-9]+)\\\"\\s*:\\s*(?<resource>[0-9]+)",
                RegexOptions.CultureInvariant))
            {
                result.Add(
                    int.Parse(match.Groups["realm"].Value),
                    int.Parse(match.Groups["resource"].Value));
            }

            Assert.IsTrue(result.Count > 0);
            return result;
        }

        private static string ExactBindingKey(
            int resourceId,
            string name,
            int monsterData,
            int level,
            int sourceIdentity)
        {
            return string.Join(
                "|",
                resourceId,
                name,
                monsterData,
                level,
                unchecked((uint)sourceIdentity).ToString("X8"));
        }

        private static Dictionary<string, string> ReadInventoryProfiles(string path)
        {
            string json = File.ReadAllText(path);
            var result = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (string profileJson in ReadJsonArrayObjects(json, "profiles"))
            {
                string profileKey = ReadJsonString(profileJson, "profileKey");
                result.Add(profileKey, profileJson);
            }

            Assert.IsTrue(result.Count > 0);
            return result;
        }

        private static List<string> ReadJsonArrayObjects(string json, string arrayName)
        {
            Match arrayMember = Regex.Match(
                json,
                "\\\"" + Regex.Escape(arrayName) + "\\\"\\s*:\\s*\\[",
                RegexOptions.CultureInvariant);
            Assert.IsTrue(arrayMember.Success, "Inventory is missing the " + arrayName + " array.");
            int arrayStart = json.IndexOf('[', arrayMember.Index);
            var result = new List<string>();
            bool inString = false;
            bool escaping = false;
            int objectDepth = 0;
            int objectStart = -1;
            for (int index = arrayStart + 1; index < json.Length; index++)
            {
                char value = json[index];
                if (inString)
                {
                    if (escaping)
                    {
                        escaping = false;
                    }
                    else if (value == '\\')
                    {
                        escaping = true;
                    }
                    else if (value == '"')
                    {
                        inString = false;
                    }

                    continue;
                }

                if (value == '"')
                {
                    inString = true;
                    continue;
                }

                if (value == '{')
                {
                    if (objectDepth == 0)
                    {
                        objectStart = index;
                    }

                    objectDepth++;
                    continue;
                }

                if (value == '}')
                {
                    objectDepth--;
                    Assert.IsTrue(objectDepth >= 0, "Inventory profiles JSON is unbalanced.");
                    if (objectDepth == 0 && objectStart >= 0)
                    {
                        result.Add(json.Substring(objectStart, index - objectStart + 1));
                        objectStart = -1;
                    }

                    continue;
                }

                if (value == ']' && objectDepth == 0)
                {
                    break;
                }
            }

            return result;
        }

        private static string ReadJsonString(string jsonObject, string name)
        {
            Match match = Regex.Match(
                jsonObject,
                "\\\"" + Regex.Escape(name)
                + "\\\"\\s*:\\s*\\\"(?<value>(?:\\\\.|[^\\\"])*)\\\"",
                RegexOptions.CultureInvariant);
            Assert.IsTrue(match.Success, "JSON record is missing string field " + name + ".");
            return Regex.Unescape(match.Groups["value"].Value);
        }

        private static int ReadJsonInt(string jsonObject, string name)
        {
            Match match = Regex.Match(
                jsonObject,
                "\\\"" + Regex.Escape(name) + "\\\"\\s*:\\s*(?<value>-?[0-9]+)",
                RegexOptions.CultureInvariant);
            Assert.IsTrue(match.Success, "JSON record is missing integer field " + name + ".");
            return int.Parse(match.Groups["value"].Value);
        }

        private static string ReadInventoryHeader(string path)
        {
            var header = new StringBuilder();
            using (var reader = new StreamReader(path))
            {
                string line;
                while ((line = reader.ReadLine()) != null)
                {
                    if (line.TrimStart().StartsWith("\"sessions\"", StringComparison.Ordinal))
                    {
                        break;
                    }

                    header.AppendLine(line);
                }
            }

            return header.ToString();
        }

        private static int ReadSummaryValue(string inventoryHeader, string name)
        {
            Match match = Regex.Match(
                inventoryHeader,
                "\\\"" + Regex.Escape(name) + "\\\"\\s*:\\s*(?<value>-?[0-9]+)",
                RegexOptions.CultureInvariant);
            Assert.IsTrue(match.Success, "Inventory header is missing " + name + ".");
            return int.Parse(match.Groups["value"].Value);
        }

        private static int ReadRuntimeGeneratedDefinitionCount(string inventoryHeader)
        {
            return inventoryHeader.IndexOf(
                       "\"runtimeGeneratedSemanticDefinitions\"",
                       StringComparison.Ordinal) >= 0
                ? ReadSummaryValue(inventoryHeader, "runtimeGeneratedSemanticDefinitions")
                : ReadSummaryValue(inventoryHeader, "captureCertifiedSemanticDefinitions");
        }

        private static string FindRepositoryRoot()
        {
            DirectoryInfo current = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory);
            while (current != null)
            {
                if (File.Exists(Path.Combine(current.FullName, "AI_START_HERE.md")))
                {
                    return current.FullName;
                }

                current = current.Parent;
            }

            Assert.Fail("Could not locate the AORebirth repository root.");
            return string.Empty;
        }
    }
}
