namespace AORebirth.Core.GameData
{
    using System.Collections.Generic;

    /// <summary>
    /// Contract for GameData\DynelCollision.json: the collision sphere the client gives a placed dynel, so a walk-in
    /// door or entrance triggers where the client predicts. The client builds one torso sphere per visual dynel from its
    /// mesh (n3VisualDynel_t::UpdateCollision, N3.dll 0x10019be4): radius TorsoSphereRadius x scale, centred
    /// TorsoSphereCenter.y x scale above the dynel. A walk-in event fires when the player's own sphere touches it.
    /// Generated by RDBDataExtractor from the client's item templates and meshes.
    /// </summary>
    public sealed class DynelCollisionData
    {
        public const int SupportedSchemaVersion = 1;

        public int SchemaVersion { get; set; }

        /// <summary>The player body's sphere (every breed's body mesh carries the same one).</summary>
        public CollisionSphereData PlayerSphere { get; set; }

        /// <summary>Sphere per item template id (doors, mission entrances); templates without a mesh are absent.</summary>
        public Dictionary<string, CollisionSphereData> Templates { get; set; }
    }

    public sealed class CollisionSphereData
    {
        public float Radius { get; set; }

        /// <summary>Height of the sphere's centre above the dynel's position.</summary>
        public float CenterY { get; set; }
    }
}
