$path = 'AORebirth\Libraries\Source\AOtomation\AOtomation.Messaging\src\SmokeLounge.AOtomation.Messaging.Tests\PlayfieldLifecycleTraceTests.cs'
$t = Get-Content -Raw $path
$t = $t.Replace('EmptyLifetimeSeconds == 30.0', 'EmptyLifetimeSeconds == 0.0')
$t = $t.Replace('UnlootedLifetimeSeconds == 120.0', 'UnlootedLifetimeSeconds == 60.0')
$t = $t.Replace('LootedCleanupSeconds == 30.0', 'LootedCleanupSeconds == 0.0')
$t = $t.Replace('Assert.AreEqual(30.0, looter.Corpse.EmptyLifetimeSeconds);', 'Assert.AreEqual(0.0, looter.Corpse.EmptyLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(120.0, looter.Corpse.UnlootedLifetimeSeconds);', 'Assert.AreEqual(60.0, looter.Corpse.UnlootedLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, looter.Corpse.LootedCleanupSeconds);', 'Assert.AreEqual(0.0, looter.Corpse.LootedCleanupSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, mugger.Corpse.EmptyLifetimeSeconds);', 'Assert.AreEqual(0.0, mugger.Corpse.EmptyLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(120.0, mugger.Corpse.UnlootedLifetimeSeconds);', 'Assert.AreEqual(60.0, mugger.Corpse.UnlootedLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, mugger.Corpse.LootedCleanupSeconds);', 'Assert.AreEqual(0.0, mugger.Corpse.LootedCleanupSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, derangedShopper.Corpse.EmptyLifetimeSeconds);', 'Assert.AreEqual(0.0, derangedShopper.Corpse.EmptyLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(120.0, derangedShopper.Corpse.UnlootedLifetimeSeconds);', 'Assert.AreEqual(60.0, derangedShopper.Corpse.UnlootedLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, derangedShopper.Corpse.LootedCleanupSeconds);', 'Assert.AreEqual(0.0, derangedShopper.Corpse.LootedCleanupSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, discardedPet.Corpse.EmptyLifetimeSeconds);', 'Assert.AreEqual(0.0, discardedPet.Corpse.EmptyLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(120.0, discardedPet.Corpse.UnlootedLifetimeSeconds);', 'Assert.AreEqual(60.0, discardedPet.Corpse.UnlootedLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, discardedPet.Corpse.LootedCleanupSeconds);', 'Assert.AreEqual(0.0, discardedPet.Corpse.LootedCleanupSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, bloodcreeper.Corpse.EmptyLifetimeSeconds);', 'Assert.AreEqual(0.0, bloodcreeper.Corpse.EmptyLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(120.0, bloodcreeper.Corpse.UnlootedLifetimeSeconds);', 'Assert.AreEqual(60.0, bloodcreeper.Corpse.UnlootedLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, bloodcreeper.Corpse.LootedCleanupSeconds);', 'Assert.AreEqual(0.0, bloodcreeper.Corpse.LootedCleanupSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, stimFiend.Corpse.EmptyLifetimeSeconds);', 'Assert.AreEqual(0.0, stimFiend.Corpse.EmptyLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(120.0, stimFiend.Corpse.UnlootedLifetimeSeconds);', 'Assert.AreEqual(60.0, stimFiend.Corpse.UnlootedLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, stimFiend.Corpse.LootedCleanupSeconds);', 'Assert.AreEqual(0.0, stimFiend.Corpse.LootedCleanupSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, neuralBurnout.Corpse.EmptyLifetimeSeconds);', 'Assert.AreEqual(0.0, neuralBurnout.Corpse.EmptyLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(120.0, neuralBurnout.Corpse.UnlootedLifetimeSeconds);', 'Assert.AreEqual(60.0, neuralBurnout.Corpse.UnlootedLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, neuralBurnout.Corpse.LootedCleanupSeconds);', 'Assert.AreEqual(0.0, neuralBurnout.Corpse.LootedCleanupSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, uncontrollableAnger.Corpse.EmptyLifetimeSeconds);', 'Assert.AreEqual(0.0, uncontrollableAnger.Corpse.EmptyLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(120.0, uncontrollableAnger.Corpse.UnlootedLifetimeSeconds);', 'Assert.AreEqual(60.0, uncontrollableAnger.Corpse.UnlootedLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, uncontrollableAnger.Corpse.LootedCleanupSeconds);', 'Assert.AreEqual(0.0, uncontrollableAnger.Corpse.LootedCleanupSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, incompleteRebuild.Corpse.EmptyLifetimeSeconds);', 'Assert.AreEqual(0.0, incompleteRebuild.Corpse.EmptyLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(120.0, incompleteRebuild.Corpse.UnlootedLifetimeSeconds);', 'Assert.AreEqual(60.0, incompleteRebuild.Corpse.UnlootedLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, incompleteRebuild.Corpse.LootedCleanupSeconds);', 'Assert.AreEqual(0.0, incompleteRebuild.Corpse.LootedCleanupSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, fragmentedSoul.Corpse.EmptyLifetimeSeconds);', 'Assert.AreEqual(0.0, fragmentedSoul.Corpse.EmptyLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(120.0, fragmentedSoul.Corpse.UnlootedLifetimeSeconds);', 'Assert.AreEqual(60.0, fragmentedSoul.Corpse.UnlootedLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, fragmentedSoul.Corpse.LootedCleanupSeconds);', 'Assert.AreEqual(0.0, fragmentedSoul.Corpse.LootedCleanupSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, redundantScan.Corpse.EmptyLifetimeSeconds);', 'Assert.AreEqual(0.0, redundantScan.Corpse.EmptyLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(120.0, redundantScan.Corpse.UnlootedLifetimeSeconds);', 'Assert.AreEqual(60.0, redundantScan.Corpse.UnlootedLifetimeSeconds);')
$t = $t.Replace('Assert.AreEqual(30.0, redundantScan.Corpse.LootedCleanupSeconds);', 'Assert.AreEqual(0.0, redundantScan.Corpse.LootedCleanupSeconds);')
$t = $t.Replace("30.0,`r`n                120.0,`r`n                30.0", "0.0,`r`n                60.0,`r`n                0.0")
$t = $t.Replace("30.0,`n                120.0,`n                30.0", "0.0,`n                60.0,`n                0.0")
Set-Content -Path $path -Value $t -NoNewline
Write-Output 'updated'
