from pathlib import Path

out = Path(r"AORebirth/Server/ZoneEngine/Core/Thrak/Quests/ThrakGardenKeyPacketSender.cs")
packs = [
    ("Veronica", "5556893A", "_tmp_thrak_qfu_veronica_5556893A.hex"),
    ("Insignia", "55563C16", "_tmp_thrak_qfu_insignia_55563C16.hex"),
    ("VeronicaUpdated", "55563C17", "_tmp_thrak_qfu_unknown_middle_55563C17.hex"),
    ("Garden", "55563C18", "_tmp_thrak_qfu_garden_55563C18.hex"),
    ("Souls", "5556591A", "_tmp_thrak_qfu_souls_5556591A.hex"),
    ("Return", "5556893D", "_tmp_thrak_qfu_return_5556893D.hex"),
]

lines = []
a = lines.append
a("namespace ZoneEngine.Core.Thrak.Quests")
a("{")
a("    #region Usings ...")
a("")
a("    using System;")
a("")
a("    using AORebirth.Core.Entities;")
a("")
a("    using SmokeLounge.AOtomation.Messaging.GameData;")
a("    using SmokeLounge.AOtomation.Messaging.Messages.N3Messages;")
a("")
a("    using Utility;")
a("")
a("    using ZoneEngine.Core;")
a("")
a("    #endregion")
a("")
a("    /// <summary>")
a("    /// Capture-backed Thrak garden-key QuestFullUpdate packets (20260718-185306).")
a("    /// Patches recipient SimpleChar instance then enqueues raw bytes into the mission window.")
a("    /// </summary>")
a("    internal static class ThrakGardenKeyPacketSender")
a("    {")
a("        private const int CapturedCharacterInstance = unchecked((int)0x765A690A);")
a("        private const int MissionIdentityType = 0x0000DAC3;")
a("")

for name, mid, fn in packs:
    hx = (Path("tools-temp") / fn).read_text(encoding="ascii").strip()
    a(f"        private const string {name}QuestFullUpdateHex =")
    a(f'            "{hx}";')
    a("")

a("        internal static bool TrySendQuestFullUpdate(ICharacter character, string questId)")
a("        {")
a("            string hex = ResolveHex(questId);")
a("            return !string.IsNullOrEmpty(hex) && TrySendRaw(character, hex);")
a("        }")
a("")
a("        internal static bool TrySendQuestDelete(ICharacter character, string questId)")
a("        {")
a("            int instance;")
a("            if (!TryResolveMissionInstance(questId, out instance) || !CanSend(character))")
a("            {")
a("                return false;")
a("            }")
a("")
a("            try")
a("            {")
a("                var client = character.Controller.Client as ZoneClient;")
a("                client.SendCompressed(")
a("                    new QuestMessage")
a("                    {")
a("                        Identity = character.Identity,")
a("                        Unknown = 0,")
a("                        Action = QuestAction.Delete,")
a("                        Unknown1 = 0,")
a("                        Mission = new Identity { Type = (IdentityType)MissionIdentityType, Instance = instance },")
a("                        Unknown2 = 0,")
a("                        Unknown3 = 0")
a("                    });")
a("                return true;")
a("            }")
a("            catch (Exception exception)")
a("            {")
a('                LogUtil.Debug(DebugInfoDetail.Error, "THRAK_GARDEN_KEY QuestDelete failed: " + exception.Message);')
a("                return false;")
a("            }")
a("        }")
a("")
a("        private static string ResolveHex(string questId)")
a("        {")
a("            if (string.IsNullOrWhiteSpace(questId))")
a("            {")
a("                return null;")
a("            }")
a("")
a("            if (string.Equals(questId, ThrakGardenKeyInteractionRules.QuestVeronica, StringComparison.OrdinalIgnoreCase))")
a("            {")
a("                return VeronicaQuestFullUpdateHex;")
a("            }")
a("")
a("            if (string.Equals(questId, ThrakGardenKeyInteractionRules.QuestInsignia, StringComparison.OrdinalIgnoreCase))")
a("            {")
a("                return InsigniaQuestFullUpdateHex;")
a("            }")
a("")
a('            if (string.Equals(questId, "Mission:55563C17", StringComparison.OrdinalIgnoreCase))')
a("            {")
a("                return VeronicaUpdatedQuestFullUpdateHex;")
a("            }")
a("")
a("            if (string.Equals(questId, ThrakGardenKeyInteractionRules.QuestGarden, StringComparison.OrdinalIgnoreCase))")
a("            {")
a("                return GardenQuestFullUpdateHex;")
a("            }")
a("")
a("            if (string.Equals(questId, ThrakGardenKeyInteractionRules.QuestSouls, StringComparison.OrdinalIgnoreCase))")
a("            {")
a("                return SoulsQuestFullUpdateHex;")
a("            }")
a("")
a("            if (string.Equals(questId, ThrakGardenKeyInteractionRules.QuestReturn, StringComparison.OrdinalIgnoreCase))")
a("            {")
a("                return ReturnQuestFullUpdateHex;")
a("            }")
a("")
a("            return null;")
a("        }")
a("")
a("        private static bool TryResolveMissionInstance(string questId, out int instance)")
a("        {")
a("            instance = 0;")
a("            if (string.IsNullOrWhiteSpace(questId))")
a("            {")
a("                return false;")
a("            }")
a("")
a("            string normalized = questId.Trim();")
a("            int colon = normalized.LastIndexOf(':');")
a("            string hex = colon >= 0 ? normalized.Substring(colon + 1) : normalized;")
a("            return int.TryParse(")
a("                hex,")
a("                System.Globalization.NumberStyles.HexNumber,")
a("                System.Globalization.CultureInfo.InvariantCulture,")
a("                out instance);")
a("        }")
a("")
a("        private static bool TrySendRaw(ICharacter character, string hex)")
a("        {")
a("            if (!CanSend(character) || string.IsNullOrWhiteSpace(hex))")
a("            {")
a("                return false;")
a("            }")
a("")
a("            try")
a("            {")
a("                var client = character.Controller.Client as ZoneClient;")
a("                byte[] packet = HexToBytes(hex);")
a("                ReplaceInstance(packet, CapturedCharacterInstance, character.Identity.Instance);")
a("                client.EnqueueOutboundCompressedBuffer(packet);")
a("                return true;")
a("            }")
a("            catch (Exception exception)")
a("            {")
a('                LogUtil.Debug(DebugInfoDetail.Error, "THRAK_GARDEN_KEY QuestFullUpdate failed: " + exception.Message);')
a("                return false;")
a("            }")
a("        }")
a("")
a("        private static bool CanSend(ICharacter character)")
a("        {")
a("            return character != null")
a("                   && character.Controller != null")
a("                   && character.Controller.Client is ZoneClient;")
a("        }")
a("")
a("        private static void ReplaceInstance(byte[] packet, int from, int to)")
a("        {")
a("            byte f0 = (byte)(from >> 24);")
a("            byte f1 = (byte)(from >> 16);")
a("            byte f2 = (byte)(from >> 8);")
a("            byte f3 = (byte)from;")
a("")
a("            for (int i = 0; i + 4 <= packet.Length; i++)")
a("            {")
a("                if (packet[i] == f0 && packet[i + 1] == f1 && packet[i + 2] == f2 && packet[i + 3] == f3)")
a("                {")
a("                    packet[i] = (byte)(to >> 24);")
a("                    packet[i + 1] = (byte)(to >> 16);")
a("                    packet[i + 2] = (byte)(to >> 8);")
a("                    packet[i + 3] = (byte)to;")
a("                    i += 3;")
a("                }")
a("            }")
a("        }")
a("")
a("        private static byte[] HexToBytes(string hex)")
a("        {")
a("            int length = hex.Length / 2;")
a("            byte[] bytes = new byte[length];")
a("            for (int i = 0; i < length; i++)")
a("            {")
a("                bytes[i] = Convert.ToByte(hex.Substring(i * 2, 2), 16);")
a("            }")
a("")
a("            return bytes;")
a("        }")
a("    }")
a("}")

out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("wrote", out, "bytes", out.stat().st_size)
