csv_path = r"C:\Users\nermi\source\repos\AORebirth\tools-temp\_tmp_team_ranges.csv"
out_path = r"C:\Users\nermi\source\repos\AORebirth\AORebirth\Server\ChatEngine\Lists\TeamLevelRanges.cs"
with open(csv_path, "r", encoding="utf-8") as f:
    body = f.read().strip().replace("\r\n", "\n")

parts = []
parts.append("using System;")
parts.append("using System.Collections.Generic;")
parts.append("using System.Globalization;")
parts.append("")
parts.append("namespace ChatEngine.Lists")
parts.append("{")
parts.append("    /// <summary>")
parts.append("    /// Team level windows used by Looking for Team filtering.")
parts.append("    /// Source: Mike Desktop mission level.txt (!lvl N → Team min-max).")
parts.append("    /// </summary>")
parts.append("    public static class TeamLevelRanges")
parts.append("    {")
parts.append("        private static readonly Dictionary<int, Tuple<int, int>> Ranges = LoadEmbedded();")
parts.append("")
parts.append("        public static bool TryGetRange(int level, out int minLevel, out int maxLevel)")
parts.append("        {")
parts.append("            Tuple<int, int> range;")
parts.append("            if (Ranges.TryGetValue(level, out range))")
parts.append("            {")
parts.append("                minLevel = range.Item1;")
parts.append("                maxLevel = range.Item2;")
parts.append("                return true;")
parts.append("            }")
parts.append("")
parts.append("            minLevel = Math.Max(1, level - 5);")
parts.append("            maxLevel = level + 5;")
parts.append("            return false;")
parts.append("        }")
parts.append("")
parts.append("        public static bool IsCompatible(int searcherLevel, int candidateLevel)")
parts.append("        {")
parts.append("            int min;")
parts.append("            int max;")
parts.append("            TryGetRange(searcherLevel, out min, out max);")
parts.append("            return candidateLevel >= min && candidateLevel <= max;")
parts.append("        }")
parts.append("")
parts.append("        private static Dictionary<int, Tuple<int, int>> LoadEmbedded()")
parts.append("        {")
parts.append("            var map = new Dictionary<int, Tuple<int, int>>();")
parts.append("            string[] lines = EmbeddedCsv.Split(new[] { '\\n', '\\r' }, StringSplitOptions.RemoveEmptyEntries);")
parts.append("            foreach (string line in lines)")
parts.append("            {")
parts.append("                string[] parts = line.Split(',');")
parts.append("                if (parts.Length != 3)")
parts.append("                {")
parts.append("                    continue;")
parts.append("                }")
parts.append("")
parts.append("                int level;")
parts.append("                int min;")
parts.append("                int max;")
parts.append("                if (!int.TryParse(parts[0], NumberStyles.Integer, CultureInfo.InvariantCulture, out level)")
parts.append("                    || !int.TryParse(parts[1], NumberStyles.Integer, CultureInfo.InvariantCulture, out min)")
parts.append("                    || !int.TryParse(parts[2], NumberStyles.Integer, CultureInfo.InvariantCulture, out max))")
parts.append("                {")
parts.append("                    continue;")
parts.append("                }")
parts.append("")
parts.append("                map[level] = Tuple.Create(min, max);")
parts.append("            }")
parts.append("")
parts.append("            return map;")
parts.append("        }")
parts.append("")
parts.append("        // level,teamMin,teamMax")
parts.append('        private const string EmbeddedCsv =')
parts.append('@"' + body + '";')
parts.append("    }")
parts.append("}")
parts.append("")

text = "\n".join(parts)
# fix the python-escaped newlines in Split to actual C# source
text = text.replace("new[] { '\\\\n', '\\\\r' }", "new[] { '\\n', '\\r' }")
# The join already has single backslash from python string '\\n' -> \n in output which is wrong
# In parts.append I used '\\n' which becomes \n in the file - need '\\n' as two chars backslash-n in C#
text = "\n".join(parts)
# Rebuild Split line properly:
fixed = []
for line in text.split("\n"):
    if "EmbeddedCsv.Split" in line:
        fixed.append('            string[] lines = EmbeddedCsv.Split(new[] { \'\\n\', \'\\r\' }, StringSplitOptions.RemoveEmptyEntries);')
    else:
        fixed.append(line)
text = "\n".join(fixed) + "\n"

with open(out_path, "w", encoding="utf-8", newline="\n") as f:
    f.write(text)
print("ok")
