<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../AORebirth/Libraries/Source/AORebirth.World.Pathfinding/AORebirth.World.Pathfinding.csproj" />
  </ItemGroup>
</Project>
