<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>7.3</LangVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Stage2ContractFingerprint.cs" Link="Stage2ContractFingerprint.cs" />
    <Compile Include="../Stage4ContractFingerprint.cs" Link="Stage4ContractFingerprint.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AORebirth.Communication">
      <HintPath>../../../AORebirth/Libraries/Source/AORebirth.Communication/bin/Debug/AORebirth.Communication.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Cell.Core">
      <HintPath>../../../AORebirth/Libraries/Source/Cell.Core/Bin/Debug/Cell.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Cell.Util">
      <HintPath>../../../AORebirth/Libraries/Source/Cell.Util/bin/Debug/Cell.Util.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Ionic.Zlib">
      <HintPath>../../../AORebirth/packages/Ionic.Zlib.1.9.1.5/lib/Ionic.Zlib.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MemBus">
      <HintPath>../../../AORebirth/packages/MemBus.2.0.2/lib/Net40-Client/MemBus.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MsgPack">
      <HintPath>../../../AORebirth/Libraries/Source/msgpack-cli/src/MsgPack.Mono/bin/Debug/MsgPack.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="NLog">
      <HintPath>../../../AORebirth/packages/NLog.2.1.0/lib/net40/NLog.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SmokeLounge.AOtomation.Messaging">
      <HintPath>../../../AORebirth/Libraries/Source/AOtomation/AOtomation.Messaging/src/bin/Debug/SmokeLounge.AOtomation.Messaging.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Utility">
      <HintPath>../../../AORebirth/Libraries/Source/Utility/bin/Debug/Utility.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="locales">
      <HintPath>../../../AORebirth/Libraries/Source/Translations/bin/Debug/locales.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
