#!/usr/bin/env python3
import csv, json, re, sys
from pathlib import Path
from extract_enemy_catalog import FIELDS

DYNA_URL="https://wiki.aodb.us/wiki/Dyna_Camps_by_level"
UNIQUE_URL="https://anarchyonline.fandom.com/wiki/Unique_Mobs"
BIOMARE_URL="https://anarchyonline.fandom.com/wiki/Biomare"
PANDE_URL="https://wiki.aodb.us/wiki/Pandemonium"
FAMILIES={
"reet":(3,13,["Omni Forest"],"natural ranged"),"malle":(3,5,["Omni Forest"],"natural melee"),"iguana":(5,6,["Omni Forest"],"bite"),"biofreak":(5,7,["Omni Forest"],"natural melee"),"blubbag":(6,75,["Omni Forest","Aegean","Wailing Wastes","Varmint Woods"],"natural melee"),"shadowmutant":(8,10,["Omni Forest"],"natural melee"),"tentacle mutant":(11,145,["Omni Forest","The Reck"],"natural melee"),"aquaan":(12,14,["Omni Forest"],"natural melee"),"hound":(12,14,["Omni Forest"],"bite"),"rhinoman":(15,98,["Newland Desert","Omni Forest","Varmint Woods","Aegean"],"natural melee"),"flea":(17,40,["Omni Forest","Aegean","Newland Desert"],"natural melee"),"eyemutant":(20,20,["Newland Desert"],"natural melee"),"salamander":(21,40,["Varmint Woods","Newland Desert"],"bite"),"bronto":(28,28,["Newland Desert"],"natural melee"),"buzzsaw":(30,30,["Newland Desert"],"natural melee"),"grecko":(30,30,["Newland Desert"],"bite"),"leet":(36,45,["Andromeda","Newland Desert","Varmint Woods","Aegean"],"natural melee"),"scorpiod":(40,60,["Newland Desert","Andromeda","Wailing Wastes"],"poison attack"),"snake":(40,275,["Newland Desert","Andromeda","Belial Forest","Central Artery Valley"],"bite"),"biomutant":(45,45,["Wailing Wastes"],"natural melee"),"rollerrat":(48,50,["Aegean","Wailing Wastes"],"bite"),"clawmutant":(50,50,["Wailing Wastes"],"claws"),"helperbot":(50,72,["Aegean"],"unknown ranged weapon"),"minibull":(50,50,["Newland Desert"],"natural melee"),"wasteprowler":(50,66,["Wailing Wastes","Aegean","Andromeda"],"natural melee"),"nightcrawler":(53,150,["Varmint Woods","Wailing Wastes","Andromeda","Central Artery Valley"],"natural melee"),"mantis":(54,204,["Aegean","Varmint Woods","Perpetual Wastelands"],"claws"),"breed mutant":(62,75,["Varmint Woods"],"natural melee"),"mechdog":(60,60,["Aegean"],"bite"),"shade":(60,89,["Andromeda"],"energy attack"),"anun":(75,204,["Aegean","Perpetual Wastelands","Central Artery Valley"],"natural melee"),"hammerhead":(84,90,["Andromeda","Wailing Wastes"],"natural melee"),"cyborg":(95,245,["Perpetual Wastelands","Central Artery Valley"],"unknown ranged weapon"),"enigma":(120,170,["Central Artery Valley","Belial Forest"],"natural melee"),"bileswarm":(129,160,["Varmint Woods","Belial Forest"],"natural ranged"),"ottous":(110,135,["Belial Forest"],"natural melee"),"medusa":(145,145,["The Reck"],"unknown ranged weapon"),"ninja droid":(125,170,["Belial Forest","The Reck"],"unknown melee weapon"),"quake lizard":(135,175,["Belial Forest"],"bite"),"worm":(184,190,["Perpetual Wastelands"],"natural melee"),"nanofreak":(151,205,["Belial Forest","Central Artery Valley"],"nano caster"),"pit lizard":(155,195,["Belial Forest"],"bite"),"swampghoul":(170,210,["Belial Forest"],"natural melee"),"demon":(204,210,["Perpetual Wastelands"],"natural melee")}
BOSSES=["Alpha Skincrawler","Aztur the Immortal","Bane","Abmouth Supremus","The Curator","Cuty","Ding","Eumenides","Gartua the Doorkeeper","George","Guardian of Tomorrow","Joo","Khalum","Lien the Memorystalker","Morty","Nematet the Custodian of Time","Neleb the Deranged","Oscar","Ownz","Powa","Polly","The Reanimator","Stumpy","Uklesh the Frozen","Vergil Aeneid","Cerubin The Rejected","Clan Modified A-4000","Clan Modified A-4001","Clawfinger Forefather","Commander Jocasta","Daria Marie Walzer","Dominus Facut","Dominus Jiannu","Dominus Ummoh","Elian Zuwadza","Eradicator Deimos","Escaped Gargantula","General Serverus","Hezak the Immortal","Inobak the Gelid","Iskop the Idolator","The Iron Reet","Jeru the Defiler","Jack Legchopper Menendez","Lab Director","Lord Ghasap","Ljotur the Lunatic","Mantis Queen","Morgan Le Faye","Omni-Pol Command Juggernaut","The One","Professor Van Horn","The Pest","R-2000 Vermin Disposal Unit","Special Agent Lamb","Supply Master Eel","Supply Master Smug","T.I.M","Tri Plumbo","Colonel Frank Kaehler","Commander Kelly Frederickson","Diamondine Soldier","Diamondine Trainee","Fiery Soldier","General Kaehler Jr","General Kronilis","General Nirtox","General Vivyan","High Commander Frederickson","Ian Warr","Nelly Johnson","Notum Soldier","Notum Trainee","Patricia Johnson","Peter Lee","Ris Lee","Tarasque","The Beast","The Night Heart","Aquarius","Aries","Cancer","Capricorn","Gemini","Leo","Libra","Pisces","Sagittarius","Scorpio","Taurus","Virgo"]
NONHOSTILE=("shopkeeper","merchant","vendor","recruiter","observer","clerk","technician","bartender","nurse","representative")
PLACEHOLDER=("animation","anims","tricks","test ","tester","pattern","dependancy","rejected","failed","robe ","showroom","saveanim","upgrade ","no skin")
PETS=(" pet","summon","slayerdroid","minidrone","drone pet")
COMBAT_ROLES={"alien":"alien natural attack","guard":"unknown ranged weapon","soldier":"unknown ranged weapon","striker":"unknown melee weapon","looter":"unknown melee weapon","mugger":"unknown melee weapon","hunter":"unknown ranged weapon","predator":"natural melee","commander":"unknown ranged weapon","enforcer":"unknown melee weapon","legion":"unknown melee weapon","watcher":"natural melee","guardian":"natural melee","brute":"natural melee","slayer":"unknown melee weapon","fiend":"natural melee","spirit":"energy attack","droid":"unknown ranged weapon","robot":"unknown ranged weapon","turret":"turret weapon","monster":"natural melee","burnout":"nano caster"}
def norm(s): return re.sub(r"[^a-z0-9]+"," ",(s or "").lower()).strip()
def main(root):
 out=Path(root)/"docs/generated/enemy_catalog"; cat=json.loads((out/"enemy_catalog.json").read_text(encoding="utf-8")); byname={norm(r["DisplayName"]):r for r in cat if r.get("DisplayName")}
 for r in cat:
  n=norm(r.get("DisplayName")); matches=[]
  for f,data in FAMILIES.items():
   if f in n or f.replace(" ","") in n: matches.append((f,data))
  if matches:
   f,(lo,hi,zones,attack)=max(matches,key=lambda x:len(x[0])); r.update(RecordClassification="LIKELY_ENEMY_TYPE",EnemyFamily=f,MinimumLevel=lo,MaximumLevel=hi,LevelSource=DYNA_URL,PlayfieldNames=zones,ZoneNames=zones,WeaponCategories=[attack.upper().replace(" ","_")],AttackTypes=[attack],EvidenceQuality="COMMUNITY_DOCUMENTED")
   r["UnresolvedFields"]=[x for x in r["UnresolvedFields"] if x not in ("MinimumLevel","PlayfieldIds","WeaponTemplateIds","AttackTemplateIds")]+["Exact internal weapon/attack reference"]
  elif any(x in n for x in COMBAT_ROLES):
   role=next(x for x in COMBAT_ROLES if x in n); attack=COMBAT_ROLES[role]; r.update(RecordClassification="LIKELY_ENEMY_TYPE",EnemyFamily=role,WeaponCategories=[attack.upper().replace(" ","_")],AttackTypes=[attack],EvidenceQuality="INFERRED_CORRELATION"); r["UnresolvedFields"]=[x for x in r["UnresolvedFields"] if x not in ("WeaponTemplateIds","AttackTemplateIds")]+["Exact internal weapon/attack reference"]
  elif any(x in n for x in NONHOSTILE): r.update(RecordClassification="LIKELY_NON_HOSTILE_NPC",EvidenceQuality="INFERRED_CORRELATION")
  elif any(x in n for x in PETS): r.update(RecordClassification="CONFIRMED_PET_OR_SUMMON",IsPetLike=True,EvidenceQuality="INFERRED_CORRELATION")
  elif any(x in n for x in PLACEHOLDER): r.update(RecordClassification="CONFIRMED_PLACEHOLDER_OR_INTERNAL",EvidenceQuality="INFERRED_CORRELATION")
 for boss in BOSSES:
  n=norm(boss); r=byname.get(n)
  if r: r.update(RecordClassification="CONFIRMED_BOSS",IsBoss=True,EvidenceQuality="COMMUNITY_DOCUMENTED",InternetEvidence=UNIQUE_URL); r["UnresolvedFields"]=[x for x in r["UnresolvedFields"] if x!="IsBoss"]
  else:
   key="external-"+re.sub(r"[^a-z0-9]+","-",n).strip("-"); cat.append({"CanonicalEnemyKey":key,"MonsterDataId":None,"TemplateId":None,"DynelType":"EXTERNAL_DOCUMENTED_ENEMY","DisplayName":boss,"InternalName":None,"EnemyFamily":None,"EnemyArchetype":"named boss","Faction":None,"Side":None,"ExpansionOrDataset":None,"IsAttackable":True,"IsHostileByDefault":None,"IsBoss":True,"IsUnique":True,"IsQuestEnemy":None,"IsMissionOnly":None,"IsPetLike":False,"IsTurret":False,"MinimumLevel":None,"MaximumLevel":None,"ExactLevel":100 if boss=="T.I.M" else None,"LevelSource":BIOMARE_URL if boss=="T.I.M" else None,"PlayfieldIds":[],"PlayfieldNames":["Biomare"] if boss=="T.I.M" else (["Pandemonium"] if boss in ["The Beast","The Night Heart","Aquarius","Aries","Cancer","Capricorn","Gemini","Leo","Libra","Pisces","Sagittarius","Scorpio","Taurus","Virgo"] else []),"ZoneNames":[],"DungeonNames":[],"SpawnDefinitionIds":[],"SpawnCoordinatesWhenAvailable":[],"WeaponTemplateIds":[],"WeaponNames":[],"WeaponCategories":["UNKNOWN"],"VisibleWeapon":None,"AttackTemplateIds":[],"AttackTypes":[],"DamageTypes":[],"AttackRange":None,"AttackTime":None,"RechargeTime":None,"SpecialAttacks":[],"NanoProgramIds":[],"NanoProgramNames":[],"SourceRecordIds":[],"SourceDatFiles":[],"EvidenceQuality":"COMMUNITY_DOCUMENTED","UnresolvedFields":["RDB mapping","weapon or natural attack"],"RdbPayloadSize":None,"RdbPayloadHash":None,"RecordClassification":"CONFIRMED_BOSS","InternetEvidence":UNIQUE_URL})
 cat.sort(key=lambda r:r["CanonicalEnemyKey"]); (out/"enemy_catalog.json").write_text(json.dumps(cat,indent=2,sort_keys=True)+"\n",encoding="utf-8")
 ledger=[]
 for r in cat:
  if not r["CanonicalEnemyKey"].startswith("rdb-"): continue
  name=r.get("DisplayName") or ""; ledger.append({"candidate_id":r.get("TemplateId"),"candidate_name":name,"queries_attempted":[f'RDB exact name: {name}',"bulk family match against Dyna Camps by level","bulk exact-name match against Unique Mobs"],"repository_matches":[],"dataset_matches":[r.get("EnemyFamily")] if r.get("RecordClassification")=="LIKELY_ENEMY_TYPE" else [],"web_sources_found":[r.get("LevelSource") or r.get("InternetEvidence")] if r.get("LevelSource") or r.get("InternetEvidence") else [],"classification":r.get("RecordClassification"),"fields_resolved":[x for x in ("EnemyFamily","MinimumLevel","MaximumLevel","PlayfieldNames","AttackTypes","IsBoss") if r.get(x) not in (None,[],"")],"fields_unresolved":r.get("UnresolvedFields",[]),"last_attempt_date":"2026-07-12"})
 (out/"enemy_research_progress.json").write_text(json.dumps(ledger,indent=2,sort_keys=True)+"\n",encoding="utf-8")
 sources=json.loads((out/"enemy_catalog_sources.json").read_text(encoding="utf-8")); sources["InternetSources"]=[{"Title":"Dyna Camps by level","Url":DYNA_URL,"Reliability":"COMMUNITY_DOCUMENTED"},{"Title":"Unique Mobs","Url":UNIQUE_URL,"Reliability":"COMMUNITY_DOCUMENTED"},{"Title":"Biomare","Url":BIOMARE_URL,"Reliability":"COMMUNITY_DOCUMENTED"},{"Title":"Pandemonium","Url":PANDE_URL,"Reliability":"COMMUNITY_DOCUMENTED"}]; (out/"enemy_catalog_sources.json").write_text(json.dumps(sources,indent=2,sort_keys=True)+"\n",encoding="utf-8")
 with (out/"enemy_catalog.csv").open("w",newline="",encoding="utf-8") as f:
  w=csv.DictWriter(f,fieldnames=FIELDS); w.writeheader(); [w.writerow({k:(json.dumps(r.get(k),sort_keys=True) if isinstance(r.get(k),(list,dict)) else r.get(k)) for k in FIELDS}) for r in cat]
 unresolved=[{"CanonicalEnemyKey":r["CanonicalEnemyKey"],"SourceRecordIds":r.get("SourceRecordIds",[]),"UnresolvedFields":r.get("UnresolvedFields",[])} for r in cat if r.get("UnresolvedFields")]; (out/"enemy_catalog_unresolved.json").write_text(json.dumps(unresolved,indent=2,sort_keys=True)+"\n",encoding="utf-8")
 with (out/"enemy_zone_associations.csv").open("w",newline="",encoding="utf-8") as f:
  cols=["CanonicalEnemyKey","EnemyName","Zone","PlayfieldId","Source","Confidence","Notes"]; w=csv.DictWriter(f,fieldnames=cols); w.writeheader()
  for r in cat:
   for i,z in enumerate(r.get("PlayfieldNames",[])): w.writerow({"CanonicalEnemyKey":r["CanonicalEnemyKey"],"EnemyName":r.get("DisplayName"),"Zone":z,"PlayfieldId":r.get("PlayfieldIds",[])[i] if i<len(r.get("PlayfieldIds",[])) else "","Source":r.get("LevelSource") or r.get("InternetEvidence") or "RDB text","Confidence":r.get("EvidenceQuality"),"Notes":"Documented family association" if r.get("LevelSource") else "Name-token correlation"})
 with (out/"enemy_weapon_associations.csv").open("w",newline="",encoding="utf-8") as f:
  cols=["CanonicalEnemyKey","EnemyName","Configuration","WeaponCategory","Source","Confidence","Notes"]; w=csv.DictWriter(f,fieldnames=cols); w.writeheader()
  for r in cat:
   for a in r.get("AttackTypes",[]): w.writerow({"CanonicalEnemyKey":r["CanonicalEnemyKey"],"EnemyName":r.get("DisplayName"),"Configuration":a,"WeaponCategory":"; ".join(r.get("WeaponCategories",[])),"Source":r.get("LevelSource") or r.get("InternetEvidence") or "RDB name correlation","Confidence":r.get("EvidenceQuality"),"Notes":"Category-level evidence; no exact item-template mapping"})
 print(json.dumps({"rows":len(cat),"ledger":len(ledger),"confirmed_bosses":sum(r.get("IsBoss") is True for r in cat),"likely_enemies":sum(r.get("RecordClassification")=="LIKELY_ENEMY_TYPE" for r in cat),"remaining":sum(r.get("RecordClassification")=="INSUFFICIENT_EVIDENCE" for r in cat)}))
if __name__=="__main__": main(Path(sys.argv[1]).resolve())
