CREATE TABLE `vendortemplate` (
  `Hash` varchar(7) NOT NULL,
  `Lvl` int(32) NOT NULL DEFAULT '1',
  `Name` varchar(256) NOT NULL DEFAULT "",
  `ItemTemplate` int(32) NOT NULL DEFAULT '0',
  `ShopInvHash` varchar(4) NOT NULL,
  `MinQl` int(32) DEFAULT '1',
  `MaxQl` int(32) DEFAULT '1',
  `Id` int(32) unsigned NOT NULL AUTO_INCREMENT,
  `Buy` float(3,2) NOT NULL default '0.05', -- Price Modifiere Sell item to Shop
  `Sell` float(3,2) NOT NULL default '1.00', -- Price Modifiere Buy item from Shop
  `Skill` int(3) DEFAULT '161', -- Skill that change the Basic Price of a Item CompLiter(161) for Machines, Psychology(162) for Humans (SL Garden Shops)
  PRIMARY KEY (`ID`,`Hash`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- This list is not complete and should be filled up.
--

insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AdvNB', 1, 'Basic Adventurer Crystals', 43580, 'AdvN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AgeNB', 1, 'Basic Agent Crystals', 43579, 'AgeN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BurNB', 1, 'Basic Bureaucrat Crystals', 43578, 'BurN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('DocNB', 1, 'Basic Doctor Crystals', 43577, 'DocN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EnfNB', 1, 'Basic Enforcer Crystals', 43581, 'EnfN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EngNB', 1, 'Basic Engineer Crystals', 43576, 'EngN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FixNB', 1, 'Basic Fixer Crystals', 43571, 'FixN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('GenNB', 1, 'Basic General Crystals', 43569, 'GenN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('KeeNB', 1, 'Basic Keeper Crystals', 222945, 'KeeN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MarNB', 1, 'Basic Martial Artist Crystals', 43575, 'MarN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MetNB', 1, 'Basic Meta-Physicist Crystals', 43574, 'MetN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('NanNB', 1, 'Basic Nanotechnician Crystals', 43573, 'NanN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ShaNB', 1, 'Basic Shade Crystals', 222946, 'ShaN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SolNB', 1, 'Basic Soldier Crystals', 43572, 'SolN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('TraNB', 1, 'Basic Trader Crystals', 43570, 'TraN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AdvNA', 1, 'Advanced Adventurer Crystals', 46522, 'AdvN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AgeNA', 1, 'Advanced Agent Crystals', 46520, 'AgeN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BurNA', 1, 'Advanced Bureaucrat Crystals', 46506, 'BurN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('DocNA', 1, 'Advanced Doctor Crystals', 46340, 'DocN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EnfNA', 1, 'Advanced Enforcer Crystals', 46517, 'EnfN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EngNA', 1, 'Advanced Engineer Crystals', 46339, 'EngN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FixNA', 1, 'Advanced Fixer Crystals', 46519, 'FixN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('KeeNA', 1, 'Advanced Keeper Crystals', 222947, 'KeeN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MarNA', 1, 'Advanced Martial Artists Crystals', 46510, 'MarN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MetNA', 1, 'Advanced Meta-Physicist Crystals', 46338, 'MetN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('NanNA', 1, 'Advanced Nanotechnician Crystals', 46337, 'NanN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ShaNA', 1, 'Advanced Shade Crystals', 222948, 'ShaN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SolNA', 1, 'Advanced Soldier Crystals', 46521, 'SolN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('TraNA', 1, 'Advanced Trader Crystals', 46518, 'TraN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AdvNS', 1, 'Superior Adventurer Crystals', 46516, 'AdvN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AgeNS', 1, 'Superior Agent Crystals', 46515, 'AgeN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BurNS', 1, 'Superior Bureaucrat Crystals', 46507, 'BurN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('DocNS', 1, 'Superior Doctor Crystals', 46336, 'DocN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EnfNS', 1, 'Superior Enforcer Crystals', 46511, 'EnfN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EngNS', 1, 'Superior Engineer Crystals', 46335, 'EngN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FixNS', 1, 'Superior Fixer Crystals', 46512, 'FixN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('KeeNS', 1, 'Superior Keeper Crystals', 222949, 'KeeN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MarNS', 1, 'Superior Martial Artist Crystals', 46509, 'MarN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MetNS', 1, 'Superior Meta-Physicist Crystals', 46334, 'MetN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('NanNS', 1, 'Superior Nanotechnician Crystals', 46341, 'NanN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ShaNS', 1, 'Superior Shade Crystals', 222950, 'ShaN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SolNS', 1, 'Superior Soldier Crystals', 46514, 'SolN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('TraNS', 1, 'Superior Trader Crystals', 46513, 'TraN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AdvCA', 1, 'Advanced Clan Adventurer Crystals', 93062, 'AdvN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AgeCA', 1, 'Advanced Clan Agent Crystals', 93061, 'AgeN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BurCA', 1, 'Advanced Clan Bureaucrat Crystals', 93058, 'BurN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('DocCA', 1, 'Advanced Clan Doctor Crystals', 93057, 'DocN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EnfCA', 1, 'Advanced Clan Enforcer Crystals', 93055, 'EnfN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EngCA', 1, 'Advanced Clan Engineer Crystals', 93053, 'EngN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FixCA', 1, 'Advanced Clan Fixer Crystals', 93050, 'FixN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MarCA', 1, 'Advanced Clan Martial Artists Crystals', 93049, 'MarN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MetCA', 1, 'Advanced Clan Meta-Physicist Crystals', 93047, 'MetN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('NanCA', 1, 'Advanced Clan Nanotechnician Crystals', 93044, 'NanN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SolCA', 1, 'Advanced Clan Soldier Crystals', 93043, 'SolN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('TraCA', 1, 'Advanced Clan Trader Crystals', 93041, 'TraN', 40, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AdvCB', 1, 'Basic Clan Adventurer Crystals', 90589, 'AdvN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AgeCB', 1, 'Basic Clan Agent Crystals', 90588, 'AgeN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BurCB', 1, 'Basic Clan Bureaucrat Crystals', 90587, 'BurN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('DocCB', 1, 'Basic Clan Doctor Crystals', 90586, 'DocN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EnfCB', 1, 'Basic Clan Enforcer Crystals', 90585, 'EnfN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EngCB', 1, 'Basic Clan Engineer Crystals', 90579, 'EngN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FixCB', 1, 'Basic Clan Fixer Crystals', 90576, 'FixN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('GenCB', 1, 'Basic Clan General Crystals', 90574, 'GenN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MarCB', 1, 'Basic Clan Martial Artist Crystals', 90571, 'MarN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MetCB', 1, 'Basic Clan Meta-Physicist Crystals', 90569, 'MetN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('NanCB', 1, 'Basic Clan Nanotechnician Crystals', 90567, 'NanN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SolCB', 1, 'Basic Clan Soldier Crystals', 90564, 'SolN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('TraCB', 1, 'Basic Clan Trader Crystals', 90562, 'TraN', 1, 50, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AdvCS', 1, 'Superior Clan Adventurer Crystals', 93104, 'AdvN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AgeCS', 1, 'Superior Clan Agent Crystals', 93098, 'AgeN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BurCS', 1, 'Superior Clan Bureaucrat Crystals', 93102, 'BurN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('DocCS', 1, 'Superior Clan Doctor Crystals', 93096, 'DocN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EnfCS', 1, 'Superior Clan Enforcer Crystals', 93091, 'EnfN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EngCS', 1, 'Superior Clan Engineer Crystals', 93093, 'EngN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FixCS', 1, 'Superior Clan Fixer Crystals', 93088, 'FixN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MarCS', 1, 'Superior Clan Martial Artist Crystals', 93090, 'MarN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MetCS', 1, 'Superior Clan Meta-Physicist Crystals', 93085, 'MetN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('NanCS', 1, 'Superior Clan Nanotechnician Crystals', 93086, 'NanN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SolCS', 1, 'Superior Clan Soldier Crystals', 93087, 'SolN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('TraCS', 1, 'Superior Clan Trader Crystals', 93082, 'TraN', 80, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AdvOA', 1, 'Advanced Omni-Tek Adventurer Crystals', 93063, 'AdvN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AgeOA', 1, 'Advanced Omni-Tek Agent Crystals', 93060, 'AgeN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BurOA', 1, 'Advanced Omni-Tek Bureaucrat Crystals', 93059, 'BurN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('DocOA', 1, 'Advanced Omni-Tek Doctor Crystals', 93056, 'DocN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EnfOA', 1, 'Advanced Omni-Tek Enforcer Crystals', 93054, 'EnfN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EngOA', 1, 'Advanced Omni-Tek Engineer Crystals', 93052, 'EngN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FixOA', 1, 'Advanced Omni-Tek Fixer Crystals', 93051, 'FixN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MarOA', 1, 'Advanced Omni-Tek Martial Artists Crystals', 93048, 'MarN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MetOA', 1, 'Advanced Omni-Tek Meta-Physicist Crystals', 93046, 'MetN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('NanOA', 1, 'Advanced Omni-Tek Nanotechnician Crystals', 93045, 'NanN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SolOA', 1, 'Advanced Omni-Tek Soldier Crystals', 93042, 'SolN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('TraOA', 1, 'Advanced Omni-Tek Trader Crystals', 93040, 'TraN', 40, 100, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AdvOB', 1, 'Basic Omni-Tek Adventurer Crystals', 90590, 'AdvN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AgeOB', 1, 'Basic Omni-Tek Agent Crystals', 90580, 'AgeN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BurOB', 1, 'Basic Omni-Tek Bureaucrat Crystals', 90581, 'BurN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('DocOB', 1, 'Basic Omni-Tek Doctor Crystals', 90582, 'DocN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EnfOB', 1, 'Basic Omni-Tek Enforcer Crystals', 90583, 'EnfN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EngOB', 1, 'Basic Omni-Tek Engineer Crystals', 90577, 'EngN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FixOB', 1, 'Basic Omni-Tek Fixer Crystals', 90575, 'FixN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('GenOB', 1, 'Basic Omni-Tek General Crystals', 90573, 'GenN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MarOB', 1, 'Basic Omni-Tek Martial Artist Crystals', 90570, 'MarN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MetOB', 1, 'Basic Omni-Tek Meta-Physicist Crystals', 90568, 'MetN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('NanOB', 1, 'Basic Omni-Tek Nanotechnician Crystals', 90565, 'NanN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SolOB', 1, 'Basic Omni-Tek Soldier Crystals', 90563, 'SolN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('TraOB', 1, 'Basic Omni-Tek Trader Crystals', 90561, 'TraN', 1, 50, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AdvOS', 1, 'Superior Omni-Tek Adventurer Crystals', 93105, 'AdvN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AgeOS', 1, 'Superior Omni-Tek Agent Crystals', 93099, 'AgeN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BurOS', 1, 'Superior Omni-Tek Bureaucrat Crystals', 93095, 'BurN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('DocOS', 1, 'Superior Omni-Tek Doctor Crystals', 93097, 'DocN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EnfOS', 1, 'Superior Omni-Tek Enforcer Crystals', 93092, 'EnfN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('EngOS', 1, 'Superior Omni-Tek Engineer Crystals', 93094, 'EngN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FixOS', 1, 'Superior Omni-Tek Fixer Crystals', 93089, 'FixN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MarOS', 1, 'Superior Omni-Tek Martial Artist Crystals', 93084, 'MarN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MetOS', 1, 'Superior Omni-Tek Meta-Physicist Crystals', 93079, 'MetN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('NanOS', 1, 'Superior Omni-Tek Nanotechnician Crystals', 93080, 'NanN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SolOS', 1, 'Superior Omni-Tek Soldier Crystals', 93081, 'SolN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('TraOS', 1, 'Superior Omni-Tek Trader Crystals', 93083, 'TraN', 80, 120, 0.05, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BNCO', 1, 'OT Basic Nano Clusters', 118281, 'NaCl', 1, 50, 0.06, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ANCO', 1, 'OT Advanced Nano Clusters', 118282, 'NaCl', 50, 90, 0.06, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SNCO', 1, 'OT Superior Nano Clusters', 118283, 'NaCl', 90, 200, 0.06, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BNCC', 1, 'Clan Basic Nano Clusters', 118284, 'NaCl', 1, 50, 0.04 ,1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ANCC', 1, 'Clan Advanced Nano Clusters', 118285, 'NaCl', 50, 90, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SNCC', 1, 'Clan Superior Nano Clusters', 118286, 'NaCl', 90, 200, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FNCB', 1, 'Faded Nano Clusters - Basic', 155299, 'CluF', 1, 50, 0.04, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FNCA', 1, 'Faded Nano Clusters - Advanced', 155300, 'CluF', 50, 90, 0.04, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('FNCS', 1, 'Faded Nano Clusters - Superior', 155301, 'CluF', 90, 200, 0.04, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BNCB', 1, 'Bright Nano Clusters - Basic', 155302, 'CluB', 1, 50, 0.04, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BNCA', 1, 'Bright Nano Clusters - Advanced', 155303, 'CluB', 50, 90, 0.04, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BNCS', 1, 'Bright Nano Clusters - Superior', 155307, 'CluB', 90, 200, 0.04, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SNCB', 1, 'Shining Nano Clusters - Basic', 155308, 'CluS', 1, 50, 0.04, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SNCA', 1, 'Shining Nano Clusters - Advanced', 155309, 'CluS', 50, 90, 0.04, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('SNCS', 1, 'Shining Nano Clusters - Superior', 155310, 'CluS', 90, 200, 0.04, 1, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MedS', 1, 'Superior Medic Supplies', 151975, 'Med', 70, 125, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MedA', 1, 'Advanced Medic Supplies', 99575, 'Med', 20, 90, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MedB', 1, 'Basic Medic Supplies', 99574, 'Med', 1, 20, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ToolS', 1, 'Superior Tools', 152012, 'Tool', 70, 200, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ToolA', 1, 'Advanced Tools', 152008, 'Tool', 40, 125, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ToolB', 1, 'Basic Tools', 99601, 'Tool', 1, 50, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AtkS', 1, 'Superior Attacks', 151982, 'Atk', 70, 200, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AtkA', 1, 'Advanced Attacks', 151981, 'Atk', 30, 125, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('AtkB', 1, 'Basic Attacks', 99602, 'Atk', 1, 50, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BkStS', 1, 'Superior Bookstore', 155601, 'BkSt', 100, 200, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BkStA', 1, 'Advanced Bookstore', 155600, 'BkSt', 50, 100, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('BkStB', 1, 'Basic Bookstore', 155599, 'BkSt', 1, 50, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ContG', 1, 'Containers', 99501, 'Cont', 1, 1, 0.04, 1.00, 161);
-- Live Neutral Supermarket Advanced ICC implant room terminals captured 2026-06-08 from current official client.
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCAdvI', 1, 'Basic ICC Adventurer Specific Implants', 302094, 'AdvI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCAgeI', 1, 'Basic ICC Agent Specific Implants', 302095, 'AgeI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCBurI', 1, 'Basic ICC Bureaucrat Specific Implants', 302096, 'BurI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCDocI', 1, 'Basic ICC Doctor Specific Implants', 302101, 'DocI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCEnfI', 1, 'Basic ICC Enforcer Specific Implants', 302102, 'EnfI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCEngI', 1, 'Basic ICC Engineer Specific Implants', 302103, 'EngI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCFixI', 1, 'Basic ICC Fixer Specific Implants', 302104, 'FixI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCKeeI', 1, 'Basic ICC Keeper Specific Implants', 302106, 'KeeI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCMarI', 1, 'Basic ICC Martial Artist Specific Implants', 302105, 'MarI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCMetI', 1, 'Basic ICC Meta-Physicist Specific Implants', 302097, 'MetI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCNanI', 1, 'Basic ICC Nanotechnician Specific Implants', 302098, 'NanI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCSolI', 1, 'Basic ICC Soldier Specific Implants', 302099, 'SolI', 10, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCTraI', 1, 'Basic ICC Trader Specific Implants', 302100, 'TraI', 10, 125, 0.04, 1.05, 161);
-- Live Neutral Supermarket Basic ICC nanos room terminals captured 2026-06-08 from current official client.
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCGenN', 1, 'ICC General Nano Programs', 297067, 'GenN', 1, 200, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCTraN', 1, 'ICC Trader Nano Programs', 297070, 'TraN', 1, 127, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCSolN', 1, 'ICC Soldier Nano Programs', 297069, 'SolN', 1, 119, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCShaN', 1, 'ICC Shade Nano Programs', 297068, 'ShaN', 1, 122, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCNanN', 1, 'ICC Nano-Technician Nano Programs', 297071, 'NanN', 1, 119, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCMetN', 1, 'ICC Meta-Physicist Nano Programs', 99551, 'MetN', 1, 116, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCMarN', 1, 'ICC Martial Artist Nano Programs', 99549, 'MarN', 1, 113, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCKeeN', 1, 'ICC Keeper Nano Programs', 99552, 'KeeN', 1, 124, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCFixN', 1, 'ICC Fixer Nano Programs', 99553, 'FixN', 1, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCEngN', 1, 'ICC Engineer Nano Programs', 99567, 'EngN', 1, 119, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCEnfN', 1, 'ICC Enforcer Nano Programs', 99557, 'EnfN', 1, 120, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCDocN', 1, 'ICC Doctor Nano Programs', 99559, 'DocN', 1, 119, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCBurN', 1, 'ICC Bureaucrat Nano Programs', 99558, 'BurN', 1, 142, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCAgeN', 1, 'ICC Agent Nano Programs', 99556, 'AgeN', 1, 119, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCAdvN', 1, 'ICC Adventurer Nano Programs', 99560, 'AdvN', 1, 125, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCTech', 1, 'ICC Tech Supplies', 297290, '0T95', 1, 300, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCAmmo', 1, 'ICC Ammunition', 297459, 'Ammo', 1, 1, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCPhaB', 1, 'Basic ICC Pharmacy', 297393, 'Med', 5, 100, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCPhaA', 1, 'Advanced ICC Pharmacy', 297394, 'Med', 110, 200, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCPhaS', 1, 'Superior ICC Pharmacy', 297395, 'PC1H', 200, 300, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCCnt', 1, 'ICC Containers', 297423, 'Cont', 1, 1, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCAccB', 1, 'Basic ICC Accessories', 297424, 'AcB', 1, 109, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCAccA', 1, 'Advanced ICC Accessories', 297425, 'AcA', 110, 200, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCAccS', 1, 'Superior ICC Accessories', 297426, 'AcS', 200, 300, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCArmB', 1, 'Basic ICC Armor', 297427, 'IAB', 1, 109, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCArmA', 1, 'Advanced ICC Armor', 297428, 'IAA', 110, 208, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCArmS', 1, 'Superior ICC Armor', 297429, 'IAS', 175, 220, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCWepB', 1, 'Basic ICC Weapons', 297430, 'WpB', 1, 109, 0.04, 0.56, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCWepA', 1, 'Advanced ICC Weapons', 297431, 'WpA', 110, 208, 0.04, 0.56, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCWepS', 1, 'Superior ICC Weapons', 297432, 'WpS', 175, 300, 0.04, 0.56, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCMAtk', 1, 'ICC Martial Arts Attacks', 297466, 'MAtk', 8, 300, 0.04, 1.00, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCSpWB', 1, 'Basic ICC Special Weapons', 99572, 'SpWB', 1, 93, 0.04, 0.56, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCSpWA', 1, 'Advanced ICC Special Weapons', 99573, 'SpWA', 101, 200, 0.04, 0.56, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCSpWS', 1, 'Superior ICC Special Weapons', 297470, 'SpWS', 200, 297, 0.04, 0.56, 161);
-- Live Neutral Supermarket tradeskill room vendor templates captured 2026-06-08 from current official client.
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCChB', 1, 'Basic ICC Chemical Supplies', 297433, 'ChB', 1, 200, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCChA', 1, 'Advanced ICC Chemical Supplies', 297434, 'ChA', 1, 209, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCChS', 1, 'Superior ICC Chemical Supplies', 297435, 'ChS', 1, 300, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCEngB', 1, 'Basic ICC Engineering Supplies', 297448, 'EnB', 1, 200, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCEngA', 1, 'Advanced ICC Engineering Supplies', 297449, 'EnA', 1, 208, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCEngS', 1, 'Superior ICC Engineering Supplies', 297450, 'EnS', 1, 300, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCFash', 1, 'ICC Fashion Supplies', 297457, 'Fash', 1, 1, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MiiArm', 1, 'Miiir Armwear', 99543, 'MArm', 1, 1, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MiiFoot', 1, 'Miiir Footwear', 99544, 'MFot', 1, 1, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MiiLeg', 1, 'Miiir Legwear', 99545, 'MLeg', 1, 1, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MiiHand', 1, 'Miiir Handwear', 99546, 'MHan', 1, 1, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MiiSwim', 1, 'Miiir Swimwear', 99547, 'MSwm', 1, 1, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MiiChst', 1, 'Miiir Chestwear', 99548, 'MChs', 1, 1, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MiiBack', 1, 'Miiir Backwear', 99550, 'MBak', 1, 1, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('MiiHead', 1, 'Miiir Headwear', 99554, 'MHea', 1, 1, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCOfB', 1, 'Basic ICC Office Supplies', 297443, 'OfcB', 1, 94, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCOfA', 1, 'Advanced ICC Office Supplies', 297444, 'OfcA', 1, 200, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCOfS', 1, 'Superior ICC Office Supplies', 297445, 'OfcS', 1, 200, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCSmB', 1, 'Basic ICC Smithing Supplies', 297440, 'SmB', 1, 104, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCSmA', 1, 'Advanced ICC Smithing Supplies', 297441, 'SmA', 10, 205, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCSmS', 1, 'Superior ICC Smithing Supplies', 297442, 'SmS', 10, 255, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCWsB', 1, 'Basic ICC Weapon Supplies', 297454, 'WsB', 1, 109, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCWsA', 1, 'Advanced ICC Weapon Supplies', 297455, 'WsA', 1, 208, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCWsS', 1, 'Superior ICC Weapon Supplies', 297456, 'WsS', 1, 300, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCArB', 1, 'Basic ICC Architecture Supplies', 297451, 'ArB', 6, 201, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCArA', 1, 'Advanced ICC Architecture Supplies', 297452, 'ArA', 75, 206, 0.04, 1.05, 161);
insert into `vendortemplate` (`HASH`,`lvl`,`Name`,`itemtemplate`,`ShopInvHash`,`minQL`,`maxQL`,`buy`,`sell`,`skill`) VALUES ('ICCArS', 1, 'Superior ICC Architecture Supplies', 297453, 'ArS', 75, 300, 0.04, 1.05, 161);
