// Dungeon generator viewer: generates a dungeon for one input set and writes an HTML page showing each floor,
// or sweeps many seeds and reports how many validate.
//
//   DungeonGeneratorViewer --gamedata <GameData root> [--style 324] [--seed 1234] [--floors 2] [--size 12]
//                          [--locked 5] [--out dungeon.html]
//   DungeonGeneratorViewer --gamedata <GameData root> --sweep 500 [--style 324] [--floors 2] [--size 12]
//
// Every generated layout is checked twice: by the generator's own validator (the client's door-matching rule), and
// by feeding the generated bytes through the server's DungeonCollisionBuilder, whose doors must be exactly the
// generator's paired doors plus the way in.
using System.Globalization;
using System.Text;

using AORebirth.DungeonGenerator;
using AORebirth.World.Collision;

var options = ParseArgs(args);
if (!options.TryGetValue("gamedata", out string? root) || !Directory.Exists(root))
{
    Console.Error.WriteLine("--gamedata <path to GameData> is required.");
    return 2;
}

int style = Int(options, "style", 324);
int floors = Int(options, "floors", 2);
int size = Int(options, "size", 12);
int locked = Int(options, "locked", 5);
var generator = new DungeonGenerator(root);

if (options.ContainsKey("sweep"))
{
    int count = Int(options, "sweep", 200);
    int ok = 0, crossFailed = 0, failed = 0, attemptsTotal = 0, roomsTotal = 0, sealedTotal = 0;
    for (int seed = 1; seed <= count; seed++)
    {
        try
        {
            DungeonGenerationResult result = generator.Generate(new DungeonGenerationRequest
            {
                StyleId = style, Seed = seed, FloorCount = floors, FloorSize = size, LockedDoorChancePercent = locked
            });
            attemptsTotal += result.Attempts;
            roomsTotal += result.Rooms.Count;
            sealedTotal += result.Validation.SealedDoors;
            if (CrossCheck(root, result, out string why)) ok++;
            else { crossFailed++; Console.WriteLine($"seed {seed}: cross-check failed: {why}"); }
        }
        catch (InvalidOperationException exception)
        {
            failed++;
            Console.WriteLine($"seed {seed}: {exception.Message}");
        }
    }

    Console.WriteLine(string.Format(CultureInfo.InvariantCulture,
        "style={0} floors={1} size={2} seeds={3} valid+crosschecked={4} crossCheckFailed={5} noLayout={6} avgAttempts={7:0.00} avgRooms={8:0.0} avgSealed={9:0.0}",
        style, floors, size, count, ok, crossFailed, failed,
        attemptsTotal / (double)Math.Max(1, count - failed), roomsTotal / (double)Math.Max(1, count - failed),
        sealedTotal / (double)Math.Max(1, count - failed)));
    return crossFailed + failed == 0 ? 0 : 1;
}

int seedValue = options.TryGetValue("seed", out string? seedText) ? int.Parse(seedText, CultureInfo.InvariantCulture) : Random.Shared.Next();
DungeonGenerationResult generated = generator.Generate(new DungeonGenerationRequest
{
    StyleId = style, Seed = seedValue, FloorCount = floors, FloorSize = size, LockedDoorChancePercent = locked
});
bool crossOk = CrossCheck(root, generated, out string crossWhy);
string outPath = options.TryGetValue("out", out string? o) ? o : $"dungeon-{style}-{seedValue}.html";
File.WriteAllText(outPath, Html(generated, crossOk, crossWhy));
Console.WriteLine($"style={style} seed={seedValue} floors={floors} size={size} rooms={generated.Rooms.Count} grid={generated.GridWidth}x{generated.GridHeight} attempts={generated.Attempts}");
Console.WriteLine($"valid={generated.Validation.IsValid} paired={generated.Validation.PairedDoors} sealed={generated.Validation.SealedDoors} unmatched={generated.Validation.Unmatched.Count} crossCheck={(crossOk ? "ok" : crossWhy)}");
Console.WriteLine($"wrote {Path.GetFullPath(outPath)}");
return 0;

// The server's own placement (DungeonCollisionBuilder) must find exactly our paired doors plus the way in.
static bool CrossCheck(string root, DungeonGenerationResult result, out string why)
{
    DungeonWorldLayout layout = DungeonCollisionBuilder.BuildLayout(root, result.Generator);
    int expected = result.Validation.PairedDoors + 1;
    if (layout.Doors.Count != expected)
    {
        why = $"server placed {layout.Doors.Count} doors, generator paired {result.Validation.PairedDoors} + way in";
        return false;
    }

    DungeonDoorPlacement exit = layout.Doors[0];
    if (!exit.IsExit || MathF.Abs(exit.Position.X - result.Spawn.X) > 3f || MathF.Abs(exit.Position.Z - result.Spawn.Z) > 3f)
    {
        why = $"server exit at ({exit.Position.X},{exit.Position.Z}) is not by the spawn ({result.Spawn.X},{result.Spawn.Z})";
        return false;
    }

    // The way in must be the entrance's mapped exit door (GameData/DungeonEntrances.json).
    PlacedRoom entrance = result.Rooms[0];
    int wayIn = -1;
    for (int d = 0; d < entrance.Doors.Count; d++)
    {
        (int fx, int fz) = entrance.Doors[d].FarBlock;
        if (fx < 0 || fz < 0 || fx >= result.GridWidth || fz >= result.GridHeight) { wayIn = d; break; }
    }

    if (wayIn != entrance.Shape.ExitDoor)
    {
        why = $"way in is door #{wayIn} of {entrance.Shape.Name}, mapped exit is #{entrance.Shape.ExitDoor}";
        return false;
    }

    // Every inward doorway of the entrance opens into a main hall.
    var mainHalls = DungeonEntranceMap.Load(root, result.Request.StyleId).MainHalls;
    for (int d = 0; d < entrance.Doors.Count; d++)
    {
        if (d == wayIn) continue;
        PlacedRoom? past = result.Rooms.Skip(1).FirstOrDefault(r => r.Floor == entrance.Floor && r.Doors.Any(o => o.Meets(entrance.Doors[d])));
        if (past != null && !mainHalls.Contains(past.Shape.RoomId))
        {
            why = $"room past the entrance (door #{d}) is {past.Shape.Name}, not a main hall";
            return false;
        }
    }

    // Each floor has its main hall quota: one per ten rooms of floor size, rounded, at least one.
    int quota = Math.Max(1, (int)Math.Round(Math.Clamp(result.Request.FloorSize, DungeonGenerator.MinFloorSize, DungeonGenerator.MaxFloorSize) / 10.0, MidpointRounding.AwayFromZero));
    foreach (var floorRooms in result.Rooms.GroupBy(r => r.Floor))
    {
        int halls = floorRooms.Count(r => mainHalls.Contains(r.Shape.RoomId));
        if (halls != quota)
        {
            why = $"floor {floorRooms.Key} has {halls} main halls, expected {quota}";
            return false;
        }
    }

    // District spawn points moved into each placed room (as the zone does) must land inside that room.
    string districtsPath = Path.Combine(root, "Playfields", result.Generator.Style.ToString(CultureInfo.InvariantCulture), "Districts.json");
    if (File.Exists(districtsPath))
    {
        using var json = System.Text.Json.JsonDocument.Parse(File.ReadAllText(districtsPath));
        byte[] zoneMap = Convert.FromBase64String(json.RootElement.GetProperty("zoneToDistrictMap").GetString() ?? string.Empty);
        var points = new Dictionary<int, List<System.Numerics.Vector3>>();
        foreach (var district in json.RootElement.GetProperty("districts").EnumerateArray())
        {
            var list = new List<System.Numerics.Vector3>();
            foreach (var point in district.GetProperty("spawnPoints").EnumerateArray())
            {
                var pos = point.GetProperty("position");
                list.Add(new System.Numerics.Vector3(pos[0].GetSingle(), pos[1].GetSingle(), pos[2].GetSingle()));
            }
            points[district.GetProperty("districtIndex").GetInt32()] = list;
        }

        foreach (DungeonRoomPlacement placement in layout.Placements)
        {
            int zone = placement.Template.InstanceId;
            int district = zone < zoneMap.Length ? zoneMap[zone] : zone;
            foreach (System.Numerics.Vector3 templatePoint in points.GetValueOrDefault(district) ?? [])
            {
                System.Numerics.Vector3 placed = placement.TransformTemplatePoint(templatePoint);
                if (!layout.Rooms[placement.Index].Contains(placed))
                {
                    why = $"spawn point of {placement.Template.Name} (room {placement.Index}, facing {placement.Facing}) lands outside it at ({placed.X:0.#},{placed.Z:0.#})";
                    return false;
                }
            }
        }
    }

    why = "ok";
    return true;
}

static string Html(DungeonGenerationResult result, bool crossOk, string crossWhy)
{
    const int Cell = 24;
    var page = new StringBuilder();
    page.Append("<!doctype html><html><head><meta charset=\"utf-8\"><title>Dungeon ")
        .Append(result.Request.StyleId).Append(" seed ").Append(result.Request.Seed)
        .Append("</title><style>body{font:13px system-ui,sans-serif;background:#16181d;color:#ddd;margin:16px}")
        .Append("svg{background:#0e0f12;margin:8px 0 24px;border:1px solid #333}.legend span{margin-right:14px}")
        .Append("table{border-collapse:collapse}td{padding:1px 8px;border-bottom:1px solid #2a2d33}</style></head><body>");
    page.Append("<h2>Style ").Append(result.Request.StyleId).Append(" &middot; seed ").Append(result.Request.Seed)
        .Append(" &middot; ").Append(result.Request.FloorCount).Append(" floors &middot; size ").Append(result.Request.FloorSize)
        .Append(" &middot; locked ").Append(result.Request.LockedDoorChancePercent).Append("%</h2>");
    page.Append("<p>Grid ").Append(result.GridWidth).Append('x').Append(result.GridHeight).Append(" blocks &middot; ")
        .Append(result.Rooms.Count).Append(" rooms &middot; attempts ").Append(result.Attempts)
        .Append(" &middot; <b>").Append(result.Validation.IsValid ? "valid" : "INVALID").Append("</b> (paired ")
        .Append(result.Validation.PairedDoors).Append(", sealed ").Append(result.Validation.SealedDoors)
        .Append(", unmatched ").Append(result.Validation.Unmatched.Count).Append(") &middot; server cross-check: ")
        .Append(crossOk ? "ok" : Escape(crossWhy)).Append("</p>");
    page.Append("<p class=\"legend\"><span style=\"color:#e0a040\">&#9632; entrance</span><span style=\"color:#50b0e0\">&#9632; start</span>")
        .Append("<span style=\"color:#6fbf6f\">&#9632; growth</span><span style=\"color:#9a7fd0\">&#9632; one-door cap</span>")
        .Append("<span style=\"color:#fff\">&#9679; paired door</span><span style=\"color:#777\">&#9679; sealed</span>")
        .Append("<span style=\"color:#ff4040\">&#9679; way in</span><span style=\"color:#ffd000\">&#9679; locked</span></p>");

    // Door numbering follows the server's order (exit first, then each room's doors to earlier rooms), so locks match.
    var doorOrder = new Dictionary<(int Room, int Door), int>();
    int wayIn = -1;
    for (int d = 0; d < result.Rooms[0].Doors.Count; d++)
    {
        (int fx, int fz) = result.Rooms[0].Doors[d].FarBlock;
        if (fx < 0 || fz < 0 || fx >= result.GridWidth || fz >= result.GridHeight) { wayIn = d; break; }
    }

    int next = 1;
    for (int r = 1; r < result.Rooms.Count; r++)
        for (int d = 0; d < result.Rooms[r].Doors.Count; d++)
            for (int e = 0; e < r; e++)
                if (result.Rooms[e].Floor == result.Rooms[r].Floor && result.Rooms[e].Doors.Any(other => other.Meets(result.Rooms[r].Doors[d])))
                { doorOrder[(r, d)] = next++; break; }

    for (int floor = 0; floor < result.Request.FloorCount; floor++)
    {
        int w = result.GridWidth * Cell, h = result.GridHeight * Cell;
        page.Append("<h3>Floor ").Append(floor).Append("</h3><svg width=\"").Append(w + 2).Append("\" height=\"").Append(h + 2).Append("\">");
        for (int i = 0; i <= result.GridWidth; i++)
            page.Append($"<line x1=\"{i * Cell}\" y1=\"0\" x2=\"{i * Cell}\" y2=\"{h}\" stroke=\"#1e2026\"/><line x1=\"0\" y1=\"{i * Cell}\" x2=\"{w}\" y2=\"{i * Cell}\" stroke=\"#1e2026\"/>");

        for (int r = 0; r < result.Rooms.Count; r++)
        {
            PlacedRoom room = result.Rooms[r];
            if (room.Floor != floor) continue;
            string color = r == 0 ? "#e0a040" : room.Shape.Role switch
            {
                RoomRole.Start => "#50b0e0",
                RoomRole.Terminator => "#9a7fd0",
                _ => "#6fbf6f"
            };
            foreach ((int x, int z) in room.Cells)
                page.Append($"<rect x=\"{x * Cell + 1}\" y=\"{h - (z + 1) * Cell + 1}\" width=\"{Cell - 2}\" height=\"{Cell - 2}\" fill=\"{color}\" fill-opacity=\"0.55\"><title>#{r} {Escape(room.Shape.Name)} (id {room.Shape.RoomId}, rot {room.Rotation * 90})</title></rect>");
            (int lx, int lz) = room.Cells[0];
            page.Append($"<text x=\"{lx * Cell + 3}\" y=\"{h - lz * Cell - 6}\" font-size=\"9\" fill=\"#fff\">{r}</text>");
        }

        for (int r = 0; r < result.Rooms.Count; r++)
        {
            PlacedRoom room = result.Rooms[r];
            if (room.Floor != floor) continue;
            for (int d = 0; d < room.Doors.Count; d++)
            {
                PlacedDoor door = room.Doors[d];
                double px = door.X * Cell / 10.0, py = h - door.Z * Cell / 10.0;
                string fill;
                if (r == 0 && d == wayIn) fill = "#ff4040";
                else if (doorOrder.TryGetValue((r, d), out int index))
                    fill = DungeonDoorLocks.IsLocked(result.Request.Seed, index, result.Request.LockedDoorChancePercent) ? "#ffd000" : "#fff";
                else if (result.Rooms.Any(o => o != room && o.Floor == floor && o.Doors.Any(other => other.Meets(door)))) continue;
                else fill = "#777";
                page.Append($"<circle cx=\"{px:0.#}\" cy=\"{py:0.#}\" r=\"3.2\" fill=\"{fill}\"/>");
            }
        }

        page.Append("</svg>");
    }

    page.Append("<h3>Rooms</h3><table><tr><td>#</td><td>floor</td><td>name</td><td>id</td><td>role</td><td>block</td><td>rot</td><td>doors</td></tr>");
    for (int r = 0; r < result.Rooms.Count; r++)
    {
        PlacedRoom room = result.Rooms[r];
        page.Append($"<tr><td>{r}</td><td>{room.Floor}</td><td>{Escape(room.Shape.Name)}</td><td>{room.Shape.RoomId}</td><td>{room.Shape.Role}</td><td>({room.BlockX},{room.BlockZ})</td><td>{room.Rotation * 90}</td><td>{room.Doors.Count}</td></tr>");
    }

    page.Append("</table></body></html>");
    return page.ToString();
}

static string Escape(string text) => System.Net.WebUtility.HtmlEncode(text ?? string.Empty);

static Dictionary<string, string> ParseArgs(string[] args)
{
    var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    for (int i = 0; i < args.Length; i++)
    {
        if (!args[i].StartsWith("--", StringComparison.Ordinal)) continue;
        string key = args[i][2..];
        result[key] = i + 1 < args.Length && !args[i + 1].StartsWith("--", StringComparison.Ordinal) ? args[++i] : "true";
    }

    return result;
}

static int Int(Dictionary<string, string> options, string key, int fallback)
    => options.TryGetValue(key, out string? text) && int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out int value) ? value : fallback;
