<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZoneEngine</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Prefer32Bit>True</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Utility" />
    <Reference Include="SmokeLounge.AOtomation.Messaging" />
    <Reference Include="AORebirth.Core" />
    <Reference Include="AORebirth.Enums" />
    <Reference Include="AORebirth.Database" />
    <Reference Include="System.Core" />
    <Reference Include="MsgPack" />
    <Reference Include="AORebirth.Interfaces" />
    <Reference Include="AORebirth.ObjectManager" />
    <Reference Include="MemBus" />
    <Reference Include="AORebirth.Stats" />
    <Reference Include="AORebirth.Communication" />
    <Reference Include="Cell.Core" />
    <Reference Include="Ionic.Zip" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data" />
    <Reference Include="AORebirth.Core.Exceptions" />
    <Reference Include="locales" />
    <Reference Include="NLog" />
    <Reference Include="NBug" />
    <Reference Include="PlayfieldLoader" />
    <Reference Include="System.Data.Linq" />
    <Reference Include="Dapper" />
  </ItemGroup>
</Project>