"""Enumerate generated source and content-shaped constants in the runtime graph."""
import json
import re
from pathlib import Path
root=Path(__file__).resolve().parents[1]
graph=json.loads((root/'docs/reports/NEWENGINE_CONTENT_ARCHITECTURE_GUARD.json').read_text())
entries=[]
for item in graph['files']:
    path=item['path'];p=root/path
    if not p.is_file():continue
    text=p.read_text(encoding='utf-8-sig',errors='replace')
    generated=path.endswith('.g.cs') or '<auto-generated' in text.lower()
    cases=[]
    for i,line in enumerate(text.splitlines(),1):
        if line.lstrip().startswith(('//','*')):continue
        if re.search(r'\b(?:\w*(?:template|npc|item|nano|playfield|mission|low|high)id|\w*(?:template|npc|item|nano|playfield|mission)instance)\b\s*(?:==|!=|is)\s*\d+',line,re.I):
            cases.append({'line':i,'source':line.strip(),'classification':'REVIEW_REQUIRED'})
        elif re.search(r'\bconst\s+(?:int|uint)\s+\w*(?:LowId|HighId|TemplateId|NpcId|PlayfieldId)\s*=\s*\d+',line):
            cases.append({'line':i,'source':line.strip(),'classification':'REVIEW_REQUIRED'})
    reasons={
        'MarketSendMessage.cs':'PROTOCOL_REQUIREMENT: zero is the empty market-entry sentinel.',
        'MarketSendMessageSerializer.cs':'PROTOCOL_REQUIREMENT: all-zero fields encode an empty market-entry slot.',
        'GameDataStore.cs':'GENERIC_DATA_VALIDATION: zero is unspecified metadata identity; any supplied identity must match the loaded playfield.',
        'NanoService.cs':'SAVED_DATA_COMPATIBILITY: zero persisted nano instance is normalized to an owned distinct identity; it selects no nano content.',
        'PlayfieldWorldSimulation.cs':'GENERIC_MECHANIC: a portal destination of zero is relative to its current playfield.'}
    for case in cases:
        if p.name in reasons:
            case['classification']=reasons[p.name].split(':')[0];case['basis']=reasons[p.name]
    if generated or cases:
        code_generation=generated and p.name=='Cell.Core.Designer.cs' and 'ResourceManager' in text
        entries.append({'path':path,'generated':generated,'generated_classification':('CODE_GENERATION' if code_generation else 'REVIEW_REQUIRED') if generated else None,'special_cases':cases})
report={'scope':'Current runtime source graph. Roslyn content guard plus origin/method review and the explicit semantic findings below; literal identity scanning alone is not a complete audit.', 'files':entries,
 'generic_mechanics_review':['PassiveRegenCalculator: native breed/stat regeneration arithmetic, no named NPC/item/content identity; generic mechanic.',
 'MartialArtsFistResolver: native skill-to-quality mechanic; weapon identities are read from editable ItemBehavior data.',
 'KillRewardResolver: native per-player contribution/rounding policy; does not contain the removed team eligibility implementation.',
 'TriggerVolumeCatalog and CellGrid: generic spatial discretization and trigger geometry, no playfield-specific exceptions.',
 'Mission DAO expiry and corpse credit bounds: fixed gameplay amounts/lifetimes removed; only structural timestamp/nonnegative-value validation remains.'],
 'unresolved_candidates':sum(c['classification']=='REVIEW_REQUIRED' for r in entries for c in r['special_cases'])+sum(r['generated_classification']=='REVIEW_REQUIRED' for r in entries)}
(root/'docs/reports/NEWENGINE_COMPILED_CONTENT_AUDIT.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(entries,indent=2))
