#!/usr/bin/env python3
"""Generate the AOSharp MissionHarvest character-level/QL resolver."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys

from generate_mission_level_graph import normalize_source, validate_canonical_csv


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = (
    REPOSITORY_ROOT
    / "AORebirth"
    / "Server"
    / "ZoneEngine"
    / "XML Data"
    / "MissionLevels.csv"
)
DEFAULT_OUTPUT = (
    REPOSITORY_ROOT
    / "Tools"
    / "AOSharpMissionOfferHarvester"
    / "MissionQlResolver.g.cs"
)
SOURCE_REPOSITORY_PATH = "AORebirth/Server/ZoneEngine/XML Data/MissionLevels.csv"
DIFFICULTY_COUNT = 11


def generate(rows: list[str], source_sha256: str) -> str:
    values: list[int] = []
    for row in rows[1:]:
        cells = row.split(",")
        values.extend(int(cells[1 + index]) for index in range(DIFFICULTY_COUNT))

    value_lines = []
    for offset in range(0, len(values), DIFFICULTY_COUNT):
        row_values = ", ".join(
            str(value) for value in values[offset : offset + DIFFICULTY_COUNT]
        )
        value_lines.append(f"            {row_values},")
    table = "\n".join(value_lines)

    return f"""// <auto-generated />
// Generated by Tools/generate_mission_harvester_ql_table.py. Do not edit by hand.
namespace AORebirth.MissionEvidence
{{
    internal static class MissionQlResolver
    {{
        internal const int MinimumCharacterLevel = 1;
        internal const int MaximumCharacterLevel = 220;
        internal const int DifficultyCount = 11;
        internal const string SourceRepositoryPath =
            \"{SOURCE_REPOSITORY_PATH}\";
        internal const string SourceSha256 =
            \"{source_sha256}\";

        private static readonly byte[] MissionQualities =
        {{
{table}
        }};

        internal static bool TryResolveFirstSlot(
            int characterLevel,
            int targetMissionQl,
            out int difficultySlot)
        {{
            difficultySlot = 0;
            if (characterLevel < MinimumCharacterLevel
                || characterLevel > MaximumCharacterLevel
                || targetMissionQl < 1
                || targetMissionQl > 250)
            {{
                return false;
            }}

            int offset = (characterLevel - MinimumCharacterLevel) * DifficultyCount;
            for (int index = 0; index < DifficultyCount; index++)
            {{
                if (MissionQualities[offset + index] == targetMissionQl)
                {{
                    difficultySlot = index + 1;
                    return true;
                }}
            }}
            return false;
        }}

        internal static bool TryGetMissionQl(
            int characterLevel,
            int difficultySlot,
            out int missionQl)
        {{
            missionQl = 0;
            if (characterLevel < MinimumCharacterLevel
                || characterLevel > MaximumCharacterLevel
                || difficultySlot < 1
                || difficultySlot > DifficultyCount)
            {{
                return false;
            }}

            int offset =
                ((characterLevel - MinimumCharacterLevel) * DifficultyCount)
                + difficultySlot
                - 1;
            missionQl = MissionQualities[offset];
            return true;
        }}
    }}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    canonical = normalize_source(args.source.read_bytes())
    rows = validate_canonical_csv(canonical)
    source_sha256 = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    generated = generate(rows, source_sha256).encode("utf-8")

    if args.check:
        if not args.output.exists() or args.output.read_bytes() != generated:
            print("MissionHarvest QL resolver is missing or stale.", file=sys.stderr)
            return 1
        print(
            "MISSION_HARVESTER_QL_TABLE=PASS "
            f"levels=220 detents=2420 source_sha256={source_sha256}"
        )
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(generated)
    print(
        f"Generated {args.output} from {args.source} "
        f"source_sha256={source_sha256}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
