<?xml version="1.0" encoding="utf-16"?>
<Project>
  <ItemGroup>
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/SolutionAssemblyInfo.cs">
      <Link>Properties/SolutionAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/ISComV2Client/ISComV2Client.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/ISComV2Client/ISComV2ClientBase.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/ISComV2Server/ISComV2ClientHandler.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/ISComV2Server/ISComV2Server.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/ChatCommand.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/CpuRamLoad.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/DynamicMessage.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/DynamicMessageCodec.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/IMessageData.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/MessageBase.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/OnlineCharacters.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/Ping.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/PrivateSystemMessage.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/RequestPlayfieldList.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/SystemChatMessage.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Messages/VicinityChatMessage.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/OnDataReceivedArgs.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/ZoneComClient.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/HandleClientRequest.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/OnMessageArgs.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/Properties/AssemblyInfo.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/ZoneCom.cs" />
    <Compile Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Communication/ZoneComServer.cs" />
  </ItemGroup>
</Project>
