<?xml version="1.0" encoding="utf-16"?>
<Project>
  <ItemGroup>
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/characterstimers.sql" Link="SqlTables/characterstimers.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/characters.sql" Link="SqlTables/characters.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/charactersactivenanos.sql" Link="SqlTables/charactersactivenanos.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/charactersmeshs.sql" Link="SqlTables/charactersmeshs.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/charactersuploadednanos.sql" Link="SqlTables/charactersuploadednanos.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/charactersperks.sql" Link="SqlTables/charactersperks.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/instanceditems.sql" Link="SqlTables/instanceditems.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/itemnames.sql" Link="SqlTables/itemnames.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/items.sql" Link="SqlTables/items.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/login.sql" Link="SqlTables/login.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/missionaccountflags.sql" Link="SqlTables/missionaccountflags.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/missionflags.sql" Link="SqlTables/missionflags.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/missionobjectiveobservations.sql" Link="SqlTables/missionobjectiveobservations.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/missionobjectiveprogress.sql" Link="SqlTables/missionobjectiveprogress.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/missionrewardledger.sql" Link="SqlTables/missionrewardledger.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/missionstates.sql" Link="SqlTables/missionstates.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/mobdroptable.sql" Link="SqlTables/mobdroptable.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/mobspawns.sql" Link="SqlTables/mobspawns.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/mobspawnsactivenanos.sql" Link="SqlTables/mobspawnsactivenanos.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/mobspawnsinventory.sql" Link="SqlTables/mobspawnsinventory.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/mobspawnsmeshs.sql" Link="SqlTables/mobspawnsmeshs.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/mobspawnsuploadednanos.sql" Link="SqlTables/mobspawnsuploadednanos.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/mobspawns_stats.sql" Link="SqlTables/mobspawns_stats.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/mobtemplate.sql" Link="SqlTables/mobtemplate.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/organizations.sql" Link="SqlTables/organizations.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/proxydestinations.sql" Link="SqlTables/proxydestinations.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/receivedmessages.sql" Link="SqlTables/receivedmessages.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/shopinventorytemplates.sql" Link="SqlTables/shopinventorytemplates.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/staticdynels.sql" Link="SqlTables/staticdynels.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/stats.sql" Link="SqlTables/stats.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/teleports.sql" Link="SqlTables/teleports.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/tradeskill.sql" Link="SqlTables/tradeskill.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/vendors.sql" Link="SqlTables/vendors.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Libraries/Source/AORebirth.Database/SqlTables/vendortemplate.sql" Link="SqlTables/vendortemplate.sql" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
