<?xml version="1.0" encoding="utf-16"?>
<Project>
  <ItemGroup>
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Config/Config.xml" Link="Config.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Captured/Arete/cleaning_robot_patrol_replay.csv" Link="Content/Captured/Arete/cleaning_robot_patrol_replay.csv" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Captured/Subway/pf127-geometry.json" Link="Content/Captured/Subway/pf127-geometry.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Official/TempleOfThreeWinds/pf1931-dungeon-geometry.json" Link="Content/Official/TempleOfThreeWinds/pf1931-dungeon-geometry.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/rex-larsson/manifest.json" Link="Content/Arete/rex-larsson/manifest.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/rex-larsson/dialogue/rex-larsson.dialogue.json" Link="Content/Arete/rex-larsson/dialogue/rex-larsson.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/rex-larsson/quests/rex-larsson.quests.json" Link="Content/Arete/rex-larsson/quests/rex-larsson.quests.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/marcus-stone/manifest.json" Link="Content/Arete/marcus-stone/manifest.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/marcus-stone/dialogue/marcus-stone.dialogue.json" Link="Content/Arete/marcus-stone/dialogue/marcus-stone.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/manifest.json" Link="Content/Arete/flint-novak/manifest.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/flint-novak.dialogue.json" Link="Content/Arete/flint-novak/dialogue/flint-novak.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/alex-gibbs.dialogue.json" Link="Content/Arete/flint-novak/dialogue/alex-gibbs.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/stan-goodman.dialogue.json" Link="Content/Arete/flint-novak/dialogue/stan-goodman.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/marco-spida.dialogue.json" Link="Content/Arete/flint-novak/dialogue/marco-spida.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/sarah-greene.dialogue.json" Link="Content/Arete/flint-novak/dialogue/sarah-greene.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/vernon-godfray.dialogue.json" Link="Content/Arete/flint-novak/dialogue/vernon-godfray.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/doctor-mason.dialogue.json" Link="Content/Arete/flint-novak/dialogue/doctor-mason.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/lorelei-bartender.dialogue.json" Link="Content/Arete/flint-novak/dialogue/lorelei-bartender.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/lolly-the-reet.dialogue.json" Link="Content/Arete/flint-novak/dialogue/lolly-the-reet.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/shipping-manifest-terminal.dialogue.json" Link="Content/Arete/flint-novak/dialogue/shipping-manifest-terminal.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/icc-immigration-officer-bill.dialogue.json" Link="Content/Arete/flint-novak/dialogue/icc-immigration-officer-bill.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/dialogue/vaughn-hammond.dialogue.json" Link="Content/Arete/flint-novak/dialogue/vaughn-hammond.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Arete/flint-novak/quests/flint-novak.quests.json" Link="Content/Arete/flint-novak/quests/flint-novak.quests.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Subway/windcaller-karrec/manifest.json" Link="Content/Subway/windcaller-karrec/manifest.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Subway/windcaller-karrec/dialogue/windcaller-karrec.dialogue.json" Link="Content/Subway/windcaller-karrec/dialogue/windcaller-karrec.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Subway/windcaller-karrec/quests/windcaller-karrec.quests.json" Link="Content/Subway/windcaller-karrec/quests/windcaller-karrec.quests.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Subway/tailor/manifest.json" Link="Content/Subway/tailor/manifest.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Subway/tailor/dialogue/tailor.dialogue.json" Link="Content/Subway/tailor/dialogue/tailor.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Thrak/garden-key/manifest.json" Link="Content/Thrak/garden-key/manifest.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Thrak/garden-vendors/manifest.json" Link="Content/Thrak/garden-vendors/manifest.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Thrak/garden-vendors/dialogue/thrak-garden-vendors.dialogue.json" Link="Content/Thrak/garden-vendors/dialogue/thrak-garden-vendors.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Thrak/garden-key/dialogue/thrak-garden-key.dialogue.json" Link="Content/Thrak/garden-key/dialogue/thrak-garden-key.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Thrak/garden-key/quests/thrak-garden-key.quests.json" Link="Content/Thrak/garden-key/quests/thrak-garden-key.quests.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Doja/nascense-chip/manifest.json" Link="Content/Doja/nascense-chip/manifest.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Doja/nascense-chip/dialogue/doja-nascense.dialogue.json" Link="Content/Doja/nascense-chip/dialogue/doja-nascense.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Doja/nascense-chip/quests/doja-nascense.quests.json" Link="Content/Doja/nascense-chip/quests/doja-nascense.quests.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Nascence/life-dialogs/manifest.json" Link="Content/Nascence/life-dialogs/manifest.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Nascence/life-dialogs/dialogue/nascence-life-dialogs.dialogue.json" Link="Content/Nascence/life-dialogs/dialogue/nascence-life-dialogs.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Andromeda/zyvania-bagh/manifest.json" Link="Content/Andromeda/zyvania-bagh/manifest.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Andromeda/zyvania-bagh/dialogue/zyvania-bagh.dialogue.json" Link="Content/Andromeda/zyvania-bagh/dialogue/zyvania-bagh.dialogue.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Content/Daily/day10-profession-nanos.json" Link="Content/Daily/day10-profession-nanos.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/Scripts/dummy.txt" Link="Scripts/dummy.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/100.xml" Link="XML Data/Districts/100.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/101.xml" Link="XML Data/Districts/101.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/102.xml" Link="XML Data/Districts/102.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/103.xml" Link="XML Data/Districts/103.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/105.xml" Link="XML Data/Districts/105.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/107.xml" Link="XML Data/Districts/107.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/109.xml" Link="XML Data/Districts/109.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/110.xml" Link="XML Data/Districts/110.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/111.xml" Link="XML Data/Districts/111.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/120.xml" Link="XML Data/Districts/120.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/124.xml" Link="XML Data/Districts/124.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/125.xml" Link="XML Data/Districts/125.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/127.xml" Link="XML Data/Districts/127.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/128.xml" Link="XML Data/Districts/128.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/152.xml" Link="XML Data/Districts/152.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/320.xml" Link="XML Data/Districts/320.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/500.xml" Link="XML Data/Districts/500.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/501.xml" Link="XML Data/Districts/501.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/505.xml" Link="XML Data/Districts/505.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Districts/800.xml" Link="XML Data/Districts/800.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Perks.xml" Link="XML Data/Perks.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/PerkActions.csv" Link="XML Data/PerkActions.csv" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/MissionRewards/ItemDb_Clusters.json" Link="XML Data/MissionRewards/ItemDb_Clusters.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/MissionRewards/ItemDB_Implants.json" Link="XML Data/MissionRewards/ItemDB_Implants.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/MissionRewards/ItemDb_Nanos.json" Link="XML Data/MissionRewards/ItemDb_Nanos.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/MissionRewards/ItemDb_Refined.json" Link="XML Data/MissionRewards/ItemDb_Refined.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/MissionRewards/ItemDb_Rest.json" Link="XML Data/MissionRewards/ItemDb_Rest.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Playfields.xml" Link="XML Data/Playfields.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/XML Data/Stats.xml" Link="XML Data/Stats.xml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(AORebirthRepositoryRoot)/AORebirth/Server/ZoneEngine/zone.ico" Link="zone.ico" />
  </ItemGroup>
</Project>
