<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>ZoneEngine_New.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.10.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.10.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZoneEngine_New\ZoneEngine_New.csproj" />
    <ProjectReference Include="../../../Tools/DatabaseMigrationTool/DatabaseMigrationTool.csproj" />
  </ItemGroup>
</Project>
